In [1]:
from IPython.display import HTML, display

html = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Curriculum-Based AI Tutor</title>

    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #0d1117;
            color: #e6edf3;
            padding: 50px;
        }

        .container {
            max-width: 900px;
            margin: auto;
            background-color: #161b22;
            padding: 40px;
            border-radius: 15px;
            border: 1px solid #30363d;
        }

        h1 {
            color: #ffffff;
            font-size: 32px;
        }

        h2 {
            color: #58a6ff;
            margin-top: 25px;
        }

        .code-box {
            background-color: #0d1117;
            border: 1px solid #30363d;
            padding: 25px;
            border-radius: 10px;
            font-family: Consolas, monospace;
            font-size: 17px;
            line-height: 1.8;
        }

        .variable {
            color: #79c0ff;
        }

        .string {
            color: #a5d6ff;
        }

        .footer {
            color: #8b949e;
            margin-top: 25px;
        }
    </style>
</head>

<body>

    <div class="container">

        <h1>Curriculum-Based AI Tutor</h1>

        <h2>Part 1: NCERT Class 8 Science Data Preparation</h2>

        <div class="code-box">
            <span class="variable">PROJECT_NAME</span>
            =
            <span class="string">"Curriculum-Based AI Tutor"</span>
            <br>

            <span class="variable">BOOK</span>
            =
            <span class="string">"NCERT Class 8 Science"</span>
        </div>

        <p class="footer">
            Project: Curriculum-Based AI Tutor | Data Preparation
        </p>

    </div>

</body>
</html>
"""

display(HTML(html))

In [2]:
from IPython.display import HTML, display

html = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <style>
        body {
            margin: 0;
            padding: 40px;
            background: #09090b;
            font-family: Arial, sans-serif;
            color: #f4f4f5;
        }

        .card {
            max-width: 850px;
            margin: auto;
            padding: 35px;
            background: linear-gradient(145deg, #18181b, #111113);
            border: 1px solid #27272a;
            border-radius: 18px;
            box-shadow: 0 15px 40px rgba(0, 0, 0, 0.5);
        }

        .badge {
            display: inline-block;
            padding: 7px 14px;
            margin-bottom: 20px;
            background: #27272a;
            color: #a1a1aa;
            border-radius: 20px;
            font-size: 13px;
            letter-spacing: 1px;
        }

        h2 {
            margin: 0;
            color: #ffffff;
            font-size: 25px;
            line-height: 1.5;
        }

        .line {
            width: 70px;
            height: 4px;
            margin: 22px 0;
            background: #6366f1;
            border-radius: 10px;
        }

        p {
            margin: 0;
            color: #d4d4d8;
            font-size: 18px;
            line-height: 1.8;
        }

        .highlight {
            color: #a5b4fc;
            font-weight: bold;
        }

        .icon {
            font-size: 25px;
            margin-right: 10px;
        }
    </style>
</head>

<body>

    <div class="card">

        <div class="badge">PROJECT STEP 01</div>

        <h2>
            <span class="icon">📚</span>
            Part 1: Download & Extract
        </h2>

        <div class="line"></div>

        <p>
            Download/extract the 
            <span class="highlight">NCERT Class 8 Science</span>
            textbook and create the 
            <span class="highlight">cleaned JSONL corpus</span>.
        </p>

    </div>

</body>
</html>
"""

display(HTML(html))

In [3]:
!pip install pypdf requests beautifulsoup4 pandas tqdm

Requirement already satisfied: pypdf in c:\users\hii\anaconda3\lib\site-packages (6.16.1)
Requirement already satisfied: requests in c:\users\hii\anaconda3\lib\site-packages (2.32.5)
Requirement already satisfied: beautifulsoup4 in c:\users\hii\anaconda3\lib\site-packages (4.13.5)
Requirement already satisfied: pandas in c:\users\hii\anaconda3\lib\site-packages (3.0.5)
Requirement already satisfied: tqdm in c:\users\hii\anaconda3\lib\site-packages (4.67.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\hii\anaconda3\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hii\anaconda3\lib\site-packages (from requests) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hii\anaconda3\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hii\anaconda3\lib\site-packages (from requests) (2025.11.12)
Requirement already satisfied: soupsieve>1.2 in c:\users\hii\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\hii\anaconda3\lib\site-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hii\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hii\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\hii\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: colorama in c:\users\hii\anaconda3\lib\site-packages (from tqdm) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\hii\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import os
import re
import json
import requests
import pandas as pd

from pypdf import PdfReader
from tqdm.auto import tqdm

In [5]:
os.makedirs("data", exist_ok=True)
os.makedirs("data/raw", exist_ok=True)
os.makedirs("data/processed", exist_ok=True)

print("Project folders created successfully.")

Project folders created successfully.

In [6]:
pdf_path = "data/raw/class8_science.pdf"

if os.path.exists(pdf_path):
    print("PDF found:", pdf_path)
else:
    print("PDF not found. Download the NCERT Class 8 Science PDF and place it in data/raw/")

PDF found: data/raw/class8_science.pdf

In [7]:
# Read the PDF 
reader = PdfReader(pdf_path)

print("Total PDF pages:", len(reader.pages))

Total PDF pages: 265

In [8]:
pages = []

for pdf_page_number, page in enumerate(
    tqdm(reader.pages),
    start=1
):
    
    text = page.extract_text()
    
    if text:
        pages.append({
            "pdf_page": pdf_page_number,
            "text": text
        })

print("Pages containing text:", len(pages))

  0%|          | 0/265 [00:00<?, ?it/s]

Pages containing text: 265

In [9]:
print(pages[0]["text"][:3000])

SCIENCE
TEXTBOOK FOR CLASS VIII
SCIENCE
2018-19

In [10]:
#Text Cleaning Function 
def clean_text(text):
    
    # Replace PDF soft-hyphen / unusual hyphen characters
    text = text.replace("\u00ad", "")
    text = text.replace("\ufffd", "")
    
    # Fix common PDF hyphenation across line breaks
    text = re.sub(
        r"(\w)[-–]\s*\n\s*(\w)",
        r"\1\2",
        text
    )
    
    # Replace multiple spaces
    text = re.sub(r"[ \t]+", " ", text)
    
    # Replace multiple newlines
    text = re.sub(r"\n+", "\n", text)
    
    # Remove spaces before punctuation
    text = re.sub(r"\s+([,.!?;:])", r"\1", text)
    
    return text.strip()

In [11]:
# Cleaning The Pages 
cleaned_pages = []

for page in tqdm(pages):
    
    cleaned = clean_text(page["text"])
    
    if len(cleaned) > 50:
        cleaned_pages.append({
            "pdf_page": page["pdf_page"],
            "text": cleaned
        })

print("Cleaned pages:", len(cleaned_pages))

  0%|          | 0/265 [00:00<?, ?it/s]

Cleaned pages: 264

In [12]:
# Checking 
print(cleaned_pages[0]["text"][:2000])

First Edition
January 2008 Magha 1929
Reprint Edition
December 2008 Pausa 1930
January 2010 Magha 1931
November 2010 Kartika 1932
January 2012 Magha 1933
November 2012 Kartika 1934
October 2013 Asvina 1935
December 2014 Pausa 1936
December 2015 Agrahayana 1937
February 2017 Magha 1938
December 2017 Agrahayana 1939
PD 750T+100T RPS
© National Council of Educational
Research and Training, 2008
` 55.00
ISBN 978-81-7450-812-6
ALL RIGHTS RESERVED
/boxshadowdwnNo part of this publication may be reproduced, stored in a retrieval
system or transmitted, in any form or by any means, electronic,
mechanical, photocopying, recording or otherwise without the prior
permission of the publisher.
/boxshadowdwnThis book is sold subject to the condition that it shall not, by way of
trade, be lent, re-sold, hired out or otherwise disposed of without the
publisher’s consent, in any form of binding or cover other than that in
which it is published.
/boxshadowdwnThe correct price of this publication is the price printed on this page,
Any revised price indicated by a rubber stamp or by a sticker or by any
other means is incorrect and should be unacceptable.
OFFICES OF THE PUBLICATION
DIVISION,, NCERT
NCERT Campus
Sri Aurobindo Marg
New Delhi 110 016 Phone: 011-26562708
108, 100 Feet Road
Hosdakere Halli Extension
Banashankari III Stage
Bangaluru 560 085 Phone: 080-26725740
Navjivan Trust Building
P.O.Navjivan
Ahmedabad 380 014 Phone: 079-27541446
CWC Campus
Opp. Dhankal Bus Stop
Panihati
Kolkata 700 114 Phone: 033-25530454
CWC Complex
Maligaon
Guwahati 781 021 Phone: 0361-2674869
Publication Team
Head, Publication: M. Siraj Anwar
Division
Chief Editor: Shveta Uppal
Chief Business: Gautam Ganguly
Manager
Chief Production: Arun Chitkara
Officer (In-charge)
Assistant Editor: Shashi Chadha
Production Assistant: Om Prakash
Cover, Layout and Illustrations
Ashwani Tyagi
Printed on 80 GSM paper with NCERT
watermark
Published at the Publication Division,
by the Secretary, National Council of
Educati

In [13]:
# Defining the Chapters 
chapters = [
    {
        "chapter_number": 1,
        "title": "Crop Production and Management",
        "printed_start_page": 1
    },
    {
        "chapter_number": 2,
        "title": "Microorganisms: Friend and Foe",
        "printed_start_page": 17
    },
    {
        "chapter_number": 3,
        "title": "Synthetic Fibres and Plastics",
        "printed_start_page": 32
    },
    {
        "chapter_number": 4,
        "title": "Materials: Metals and Non-Metals",
        "printed_start_page": 44
    },
    {
        "chapter_number": 5,
        "title": "Coal and Petroleum",
        "printed_start_page": 56
    },
    {
        "chapter_number": 6,
        "title": "Combustion and Flame",
        "printed_start_page": 64
    },
    {
        "chapter_number": 7,
        "title": "Conservation of Plants and Animals",
        "printed_start_page": 77
    },
    {
        "chapter_number": 8,
        "title": "Cell — Structure and Functions",
        "printed_start_page": 90
    },
    {
        "chapter_number": 9,
        "title": "Reproduction in Animals",
        "printed_start_page": 100
    },
    {
        "chapter_number": 10,
        "title": "Reaching the Age of Adolescence",
        "printed_start_page": 113
    },
    {
        "chapter_number": 11,
        "title": "Force and Pressure",
        "printed_start_page": 127
    },
    {
        "chapter_number": 12,
        "title": "Friction",
        "printed_start_page": 146
    },
    {
        "chapter_number": 13,
        "title": "Sound",
        "printed_start_page": 157
    },
    {
        "chapter_number": 14,
        "title": "Chemical Effects of Electric Current",
        "printed_start_page": 172
    },
    {
        "chapter_number": 15,
        "title": "Some Natural Phenomena",
        "printed_start_page": 184
    },
    {
        "chapter_number": 16,
        "title": "Light",
        "printed_start_page": 199
    },
    {
        "chapter_number": 17,
        "title": "Stars and the Solar System",
        "printed_start_page": 215
    },
    {
        "chapter_number": 18,
        "title": "Pollution of Air and Water",
        "printed_start_page": 239
    }
]

print("Number of chapters:", len(chapters))

Number of chapters: 18

In [14]:
# Detect chapter pages
def normalize_heading(text):
    text = text.upper()
    text = text.replace("—", "-")
    text = text.replace("–", "-")
    text = re.sub(r"[^A-Z0-9]+", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

In [15]:
chapter_locations = []

for chapter in chapters:
    
    target = normalize_heading(chapter["title"])
    matches = []
    
    for page in cleaned_pages:
        
        page_normalized = normalize_heading(
            page["text"]
        )
        
        if target in page_normalized:
            matches.append(page["pdf_page"])
    
    chapter_locations.append({
        **chapter,
        "pdf_pages_found": matches
    })

In [16]:
# View chapter detection
chapter_df = pd.DataFrame(chapter_locations)

chapter_df[
    [
        "chapter_number",
        "title",
        "printed_start_page",
        "pdf_pages_found"
    ]
]

,chapter_number,title,printed_start_page,pdf_pages_found
0,1,Crop Production and Management,1,"[11, 14, 16, 18, 20, 22, 24, 26, 28]"
1,2,Microorganisms: Friend and Foe,17,"[11, 30, 32, 34, 36, 38, 40, 42, 44]"
2,3,Synthetic Fibres and Plastics,32,"[11, 45, 46, 48, 50, 52, 53, 54, 56]"
3,4,Materials: Metals and Non-Metals,44,[11]
4,5,Coal and Petroleum,56,"[11, 69, 70, 72, 74, 75, 76]"
5,6,Combustion and Flame,64,"[11, 77, 78, 80, 82, 84, 86, 88]"
6,7,Conservation of Plants and Animals,77,"[11, 90, 92, 94, 96, 98, 100, 102]"
7,8,Cell — Structure and Functions,90,[]
8,9,Reproduction in Animals,100,"[11, 113, 114, 116, 118, 120, 122, 123, 124]"
9,10,Reaching the Age of Adolescence,113,"[11, 126, 128, 130, 132, 134, 136, 138]"
10,11,Force and Pressure,127,"[12, 140, 142, 144, 146, 148, 150, 152, 154, 1..."
11,12,Friction,146,"[12, 80, 148, 155, 156, 159, 160, 161, 162, 16..."
12,13,Sound,157,"[12, 58, 59, 63, 83, 170, 171, 172, 173, 174, ..."
13,14,Chemical Effects of Electric Current,172,"[185, 186, 188, 189, 190, 192, 194, 196]"
14,15,Some Natural Phenomena,184,[12]
15,16,Light,199,"[5, 12, 17, 18, 23, 27, 39, 43, 46, 50, 68, 69..."
16,17,Stars and the Solar System,215,"[12, 228, 230, 232, 234, 236, 238, 240, 242, 2..."
17,18,Pollution of Air and Water,239,"[12, 252, 254, 256, 258, 260, 262, 264]"

In [17]:
# Find the actual first occurrence
chapter_starts = []

for chapter in chapters:
    
    target = normalize_heading(chapter["title"])
    
    found_page = None
    
    for page in cleaned_pages:
        
        page_normalized = normalize_heading(
            page["text"]
        )
        
        if target in page_normalized:
            found_page = page["pdf_page"]
            break
    
    chapter_starts.append({
        "chapter_number": chapter["chapter_number"],
        "chapter": chapter["title"],
        "pdf_start_page": found_page,
        "printed_start_page": chapter["printed_start_page"]
    })

chapter_starts_df = pd.DataFrame(chapter_starts)

chapter_starts_df

,chapter_number,chapter,pdf_start_page,printed_start_page
0,1,Crop Production and Management,11.0,1
1,2,Microorganisms: Friend and Foe,11.0,17
2,3,Synthetic Fibres and Plastics,11.0,32
3,4,Materials: Metals and Non-Metals,11.0,44
4,5,Coal and Petroleum,11.0,56
5,6,Combustion and Flame,11.0,64
6,7,Conservation of Plants and Animals,11.0,77
7,8,Cell — Structure and Functions,NaN,90
8,9,Reproduction in Animals,11.0,100
9,10,Reaching the Age of Adolescence,11.0,113
10,11,Force and Pressure,12.0,127
11,12,Friction,12.0,146
12,13,Sound,12.0,157
13,14,Chemical Effects of Electric Current,185.0,172
14,15,Some Natural Phenomena,12.0,184
15,16,Light,5.0,199
16,17,Stars and the Solar System,12.0,215
17,18,Pollution of Air and Water,12.0,239

In [18]:
# Create chapter ranges safely

chapter_ranges = []

# Remove chapters where the PDF heading was not detected
valid_chapters = [
    chapter
    for chapter in chapter_starts
    if chapter["pdf_start_page"] is not None
]

# Sort chapters by their PDF starting page
valid_chapters = sorted(
    valid_chapters,
    key=lambda x: x["pdf_start_page"]
)

for i, chapter in enumerate(valid_chapters):

    start_pdf = chapter["pdf_start_page"]

    # Determine the end page
    if i < len(valid_chapters) - 1:
        next_start = valid_chapters[i + 1]["pdf_start_page"]
        end_pdf = next_start - 1
    else:
        end_pdf = len(cleaned_pages)

    chapter_ranges.append({
        "chapter_number": chapter["chapter_number"],
        "chapter": chapter["chapter"],
        "start_pdf_page": start_pdf,
        "end_pdf_page": end_pdf
    })

chapter_ranges_df = pd.DataFrame(chapter_ranges)

chapter_ranges_df

,chapter_number,chapter,start_pdf_page,end_pdf_page
0,16,Light,5,10
1,1,Crop Production and Management,11,10
2,2,Microorganisms: Friend and Foe,11,10
3,3,Synthetic Fibres and Plastics,11,10
4,4,Materials: Metals and Non-Metals,11,10
5,5,Coal and Petroleum,11,10
6,6,Combustion and Flame,11,10
7,7,Conservation of Plants and Animals,11,10
8,9,Reproduction in Animals,11,10
9,10,Reaching the Age of Adolescence,11,11
10,11,Force and Pressure,12,11
11,12,Friction,12,11
12,13,Sound,12,11
13,15,Some Natural Phenomena,12,11
14,17,Stars and the Solar System,12,11
15,18,Pollution of Air and Water,12,184
16,14,Chemical Effects of Electric Current,185,264

In [19]:
print("Detected chapters:", len(chapter_ranges_df))

display(
    chapter_ranges_df[
        [
            "chapter_number",
            "chapter",
            "start_pdf_page",
            "end_pdf_page"
        ]
    ]
)

Detected chapters: 17

,chapter_number,chapter,start_pdf_page,end_pdf_page
0,16,Light,5,10
1,1,Crop Production and Management,11,10
2,2,Microorganisms: Friend and Foe,11,10
3,3,Synthetic Fibres and Plastics,11,10
4,4,Materials: Metals and Non-Metals,11,10
5,5,Coal and Petroleum,11,10
6,6,Combustion and Flame,11,10
7,7,Conservation of Plants and Animals,11,10
8,9,Reproduction in Animals,11,10
9,10,Reaching the Age of Adolescence,11,11
10,11,Force and Pressure,12,11
11,12,Friction,12,11
12,13,Sound,12,11
13,15,Some Natural Phenomena,12,11
14,17,Stars and the Solar System,12,11
15,18,Pollution of Air and Water,12,184
16,14,Chemical Effects of Electric Current,185,264

In [20]:
for chapter in chapters:
    chapter["included"] = True

In [21]:
# Creating page-level chapter documents
chapter_pages = []

for chapter_range in chapter_ranges:
    
    for page in cleaned_pages:
        
        pdf_page = page["pdf_page"]
        
        if (
            chapter_range["start_pdf_page"]
            <= pdf_page
            <= chapter_range["end_pdf_page"]
        ):
            
            chapter_pages.append({
                "chapter_number": chapter_range["chapter_number"],
                "chapter": chapter_range["chapter"],
                "pdf_page": pdf_page,
                "text": page["text"]
            })

print(
    "Chapter page records:",
    len(chapter_pages)
)

Chapter page records: 260

In [22]:
# Creating the RAG chunks
def create_chunks(
    text,
    chunk_size=800,
    overlap=100
):
    
    words = text.split()
    
    chunks = []
    
    start = 0
    
    while start < len(words):
        
        end = min(
            start + chunk_size,
            len(words)
        )
        
        chunk = " ".join(
            words[start:end]
        )
        
        if len(chunk.strip()) > 50:
            chunks.append(chunk.strip())
        
        if end >= len(words):
            break
        
        start = end - overlap
    
    return chunks

In [23]:
# Generating the corpus
corpus = []

chunk_id = 0

for chapter_range in chapter_ranges:
    
    chapter_records = [
        record
        for record in chapter_pages
        if record["chapter_number"]
        == chapter_range["chapter_number"]
    ]
    
    # Combine pages belonging to the chapter
    combined_text = " ".join(
        record["text"]
        for record in chapter_records
    )
    
    chunks = create_chunks(
        combined_text
    )
    
    for chunk_number, chunk in enumerate(
        chunks,
        start=1
    ):
        
        corpus.append({
            "id": f"chunk_{chunk_id}",
            "chapter_number":
                chapter_range["chapter_number"],
            "chapter":
                chapter_range["chapter"],
            "chunk_number":
                chunk_number,
            "text":
                chunk
        })
        
        chunk_id += 1

print("Total chunks:", len(corpus))

Total chunks: 113

In [24]:
# Convert to DataFrame
corpus_df = pd.DataFrame(corpus)

corpus_df.head()

,id,chapter_number,chapter,chunk_number,text
0,chunk_0,16,Light,1,This book is the outcome of the efforts of the...
1,chunk_1,16,Light,2,us to talk to children through the medium of t...
2,chunk_2,16,Light,3,Head Department of Education in Science and Ma...
3,chunk_3,10,Reaching the Age of Adolescence,1,CONTENTS FOREWORD iii PREFACE v Chapter 1 CROP...
4,chunk_4,18,Pollution of Air and Water,1,Chapter 11 FORCE AND PRESSURE 127 Chapter 12 F...

In [25]:
# Checking the chapter distribution
chapter_distribution = (
    corpus_df
    .groupby(
        ["chapter_number", "chapter"]
    )
    .size()
    .reset_index(
        name="chunks"
    )
)

chapter_distribution

   chapter_number                               chapter  chunks
0              10       Reaching the Age of Adolescence       1
1              14  Chemical Effects of Electric Current      35
2              16                                 Light       3
3              18            Pollution of Air and Water      74

In [26]:
# Save the JSONL
OUTPUT_FILE = "class8_science.jsonl"

with open(
    OUTPUT_FILE,
    "w",
    encoding="utf-8"
) as f:
    
    for record in corpus:
        
        f.write(
            json.dumps(
                record,
                ensure_ascii=False
            ) + "\n"
        )

print(
    f"Saved {len(corpus)} chunks to {OUTPUT_FILE}"
)

Saved 113 chunks to class8_science.jsonl

In [27]:
# Verifieng the JSONL File 
with open(
    "class8_science.jsonl",
    "r",
    encoding="utf-8"
) as f:
    
    first_record = json.loads(
        f.readline()
    )

first_record

{'id': 'chunk_0',
 'chapter_number': 16,
 'chapter': 'Light',
 'chunk_number': 1,
 'text': 'This book is the outcome of the efforts of the textbook development committee appointed by the NCER T. The committee met a few times to interact with one another to improve the draft. Then there was a review meeting in which many experts and practicing school teachers were invited to review the draft and suggest improvements. By and large we have stuck to the format of the Class VII book. By now famous characters, Boojho and Paheli, have been used to make the text interactive. Attempt has been made to recall children’s own experiences and build concepts around them. This is designed to connect science that they study in the school with their everyday life. Many activities have been suggested to clarify concepts. Some of these activities are so simple that children can perform them on their own. The requirement of the apparatus requir ed for the activities is minimal. W e performed all the activities ourselves to ensure that there was no difficulty in performing them in the school situation. The activities should also help children in developing skills such as presentation of data in tabular and graphical forms, reasoning and drawing inference from the given data. The language of the book has been kept as simple as possible. A large number of photographs, illustrations, cartoons, etc. have been included to make the book attractive. To help teachers evaluate children effectively, a large number of exercises have been given at the end of each chapter. The teachers are encouraged to frame additional exercises to test children’s understanding. Some challenging exercises have also been devised for those children who would like to appear for the National Talent Search Examination conducted by the NCERT. We are conscious of the fact that there is a paucity of additional reading material for children. We have tried to addr ess this problem by providing non-evaluative boxes. These boxes, in light orange, contain additional information, anecdotes, stories, strange facts and other such interesting materials. We all know that children are mischievous and playful by nature. Therefore, in order to prevent any untoward incident during the performance of the activities in the school or outside, necessary cautions, in magenta, have been inserted at various places in the book. To prepare children to assume their roles as responsible citizens of tomorrow, attempt has been made to sensitise them to the issues concerning gender, religion, environment, health and hygiene, water scarcity and energy conservation. We have sought to weave into the text the value of cooperation and the importance of peer learning. An important feature of the book is what we call Extended Learning. These are totally non-evaluative, and purely voluntary activities and projects. Some of the projects in this section have been designed to enhance children’s interaction with the experts, teachers, even parents, and society at large. The children are required to collect information of various kinds and draw conclusions of their own. My request to teachers and parents is to use the book in the spirit in which it has been written. Encourage children to perform activities and learn by doing, rather than by rote. You can supplement, or even replace, the activities given here. If you Preface 2018-19 feel that you have better alter natives, especially with your local/regional flavour, please write to us so that these activities could be used in the future editions of the book. We have been able to include only a small subset of children’s experiences. You have a better knowledge of their experiences because you are in touch with them. Use them to illustrate the concepts being taught. Above all, please do not stifle children’s natural curiosity. Encourage them to ask questions, even if sometimes you feel uncomfortable. If you do not know the answer to a question on the spot, do not feel embarrassed. You can promise them to find the answer and deal with it later. Make a genuine attempt to get the answer from whatever resources are within your reach, such as senior school or college teachers, experts, libraries, internet etc. If, inspite of your efforts, you cannot get the answer to some question, you could write to NCERT. I must thank the NCERT for enabling us to talk to children through the medium of this book. Every member of the NCERT has been courteous and helpful to us. In the end, I must express my gratitude to the members of the Editing Team, who worked tirelessly to help me bring the book to the present form. If you and your students find this book useful and enjoy teaching/learning science through this book, the Editing Team and I shall consider ourselves well-rewarded. V.B. BHATIA Chief Advisor Textbook Development Committee vi 2018-19 CHAIRPERSON, ADVISORY GROUP FOR TEXTBOOKS IN SCIENCE AND MATHEMATICS J.V. Narlikar, Emeritus Professor, Inter University'}

In [28]:
# Final Validataion 
print("=" * 50)
print("CORPUS VALIDATION")
print("=" * 50)

print(
    "Total chunks:",
    len(corpus_df)
)

print(
    "Total chapters:",
    corpus_df["chapter_number"].nunique()
)

print(
    "Total characters:",
    corpus_df["text"].str.len().sum()
)

print(
    "Average chunk size:",
    round(
        corpus_df["text"].str.len().mean(),
        2
    )
)

print(
    "Minimum chunk size:",
    corpus_df["text"].str.len().min()
)

print(
    "Maximum chunk size:",
    corpus_df["text"].str.len().max()
)

==================================================
CORPUS VALIDATION
==================================================
Total chunks: 113
Total chapters: 4
Total characters: 509742
Average chunk size: 4510.99
Minimum chunk size: 468
Maximum chunk size: 5678

In [29]:
chapter_distribution

   chapter_number                               chapter  chunks
0              10       Reaching the Age of Adolescence       1
1              14  Chemical Effects of Electric Current      35
2              16                                 Light       3
3              18            Pollution of Air and Water      74

This output makes the problem clear.

This extraction itself worked, but the chapter detection method was wrong for this PDF.

# Now Let's Fix this Properly

In [30]:
if os.path.exists("class8_science.jsonl"):
    os.remove("class8_science.jsonl")

print("Old corpus deleted.")

Old corpus deleted.

In [31]:
# Replacing our Old Chapter list
chapters = [
    (1, "Crop Production and Management", 1),
    (2, "Microorganisms: Friend and Foe", 17),
    (3, "Synthetic Fibres and Plastics", 32),
    (4, "Materials: Metals and Non-Metals", 44),
    (5, "Coal and Petroleum", 56),
    (6, "Combustion and Flame", 64),
    (7, "Conservation of Plants and Animals", 77),
    (8, "Cell — Structure and Functions", 90),
    (9, "Reproduction in Animals", 100),
    (10, "Reaching the Age of Adolescence", 113),
    (11, "Force and Pressure", 127),
    (12, "Friction", 146),
    (13, "Sound", 157),
    (14, "Chemical Effects of Electric Current", 172),
    (15, "Some Natural Phenomena", 184),
    (16, "Light", 199),
    (17, "Stars and the Solar System", 215),
    (18, "Pollution of Air and Water", 239)
]

print("Total chapters:", len(chapters))

Total chapters: 18

In [32]:
# PDF page offset for this exact NCERT PDF
PDF_OFFSET = 13

chapter_ranges = []

for i, (chapter_number, title, printed_start) in enumerate(chapters):

    # Convert printed textbook page to PDF page
    pdf_start = printed_start + PDF_OFFSET

    # Next chapter's printed starting page
    if i < len(chapters) - 1:
        next_printed_start = chapters[i + 1][2]
        pdf_end = next_printed_start + PDF_OFFSET - 1
    else:
        # Chapter 18 ends before the index
        pdf_end = 252

    chapter_ranges.append({
        "chapter_number": chapter_number,
        "chapter": title,
        "printed_start_page": printed_start,
        "printed_end_page": pdf_end - PDF_OFFSET,
        "pdf_start_page": pdf_start,
        "pdf_end_page": pdf_end
    })

chapter_ranges_df = pd.DataFrame(chapter_ranges)

chapter_ranges_df

,chapter_number,chapter,printed_start_page,printed_end_page,pdf_start_page,pdf_end_page
0,1,Crop Production and Management,1,16,14,29
1,2,Microorganisms: Friend and Foe,17,31,30,44
2,3,Synthetic Fibres and Plastics,32,43,45,56
3,4,Materials: Metals and Non-Metals,44,55,57,68
4,5,Coal and Petroleum,56,63,69,76
5,6,Combustion and Flame,64,76,77,89
6,7,Conservation of Plants and Animals,77,89,90,102
7,8,Cell — Structure and Functions,90,99,103,112
8,9,Reproduction in Animals,100,112,113,125
9,10,Reaching the Age of Adolescence,113,126,126,139
10,11,Force and Pressure,127,145,140,158
11,12,Friction,146,156,159,169
12,13,Sound,157,171,170,184
13,14,Chemical Effects of Electric Current,172,183,185,196
14,15,Some Natural Phenomena,184,198,197,211
15,16,Light,199,214,212,227
16,17,Stars and the Solar System,215,238,228,251
17,18,Pollution of Air and Water,239,239,252,252

In [33]:
# Check the ranges
display(
    chapter_ranges_df[
        [
            "chapter_number",
            "chapter",
            "printed_start_page",
            "printed_end_page",
            "pdf_start_page",
            "pdf_end_page"
        ]
    ]
)

,chapter_number,chapter,printed_start_page,printed_end_page,pdf_start_page,pdf_end_page
0,1,Crop Production and Management,1,16,14,29
1,2,Microorganisms: Friend and Foe,17,31,30,44
2,3,Synthetic Fibres and Plastics,32,43,45,56
3,4,Materials: Metals and Non-Metals,44,55,57,68
4,5,Coal and Petroleum,56,63,69,76
5,6,Combustion and Flame,64,76,77,89
6,7,Conservation of Plants and Animals,77,89,90,102
7,8,Cell — Structure and Functions,90,99,103,112
8,9,Reproduction in Animals,100,112,113,125
9,10,Reaching the Age of Adolescence,113,126,126,139
10,11,Force and Pressure,127,145,140,158
11,12,Friction,146,156,159,169
12,13,Sound,157,171,170,184
13,14,Chemical Effects of Electric Current,172,183,185,196
14,15,Some Natural Phenomena,184,198,197,211
15,16,Light,199,214,212,227
16,17,Stars and the Solar System,215,238,228,251
17,18,Pollution of Air and Water,239,239,252,252

In [34]:
# Create page-level records
chapter_pages = []

for chapter in chapter_ranges:

    for page in cleaned_pages:

        pdf_page = page["pdf_page"]

        if (
            chapter["pdf_start_page"]
            <= pdf_page
            <= chapter["pdf_end_page"]
        ):

            printed_page = pdf_page - PDF_OFFSET

            chapter_pages.append({
                "chapter_number": chapter["chapter_number"],
                "chapter": chapter["chapter"],
                "pdf_page": pdf_page,
                "printed_page": printed_page,
                "text": page["text"]
            })

print("Total chapter pages:", len(chapter_pages))

Total chapter pages: 239

In [35]:
# Checking the Chapters 
page_df = pd.DataFrame(chapter_pages)

chapter_check = (
    page_df
    .groupby(
        ["chapter_number", "chapter"]
    )
    .agg(
        first_page=("printed_page", "min"),
        last_page=("printed_page", "max"),
        total_pages=("printed_page", "count")
    )
    .reset_index()
)

display(chapter_check)

,chapter_number,chapter,first_page,last_page,total_pages
0,1,Crop Production and Management,1,16,16
1,2,Microorganisms: Friend and Foe,17,31,15
2,3,Synthetic Fibres and Plastics,32,43,12
3,4,Materials: Metals and Non-Metals,44,55,12
4,5,Coal and Petroleum,56,63,8
5,6,Combustion and Flame,64,76,13
6,7,Conservation of Plants and Animals,77,89,13
7,8,Cell — Structure and Functions,90,99,10
8,9,Reproduction in Animals,100,112,13
9,10,Reaching the Age of Adolescence,113,126,14
10,11,Force and Pressure,127,145,19
11,12,Friction,146,156,11
12,13,Sound,157,171,15
13,14,Chemical Effects of Electric Current,172,183,12
14,15,Some Natural Phenomena,184,198,15
15,16,Light,199,214,16
16,17,Stars and the Solar System,215,238,24
17,18,Pollution of Air and Water,239,239,1

Better Text Cleaning

In [36]:
def clean_ncert_text(text):

    # Remove year/footer
    text = re.sub(r"\b2018[-–]19\b", " ", text)

    # Remove replacement characters
    text = text.replace("\ufffd", " ")

    # Remove soft hyphens
    text = text.replace("\u00ad", "")

    # Join words broken by line/hyphen
    text = re.sub(
        r"(\w)[-–]\s+(\w)",
        r"\1\2",
        text
    )

    # Normalize whitespace
    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text.strip()

In [37]:
# Applying Text Cleaning 
for record in chapter_pages:
    record["text"] = clean_ncert_text(
        record["text"]
    )

print("Text cleaning completed.")

Text cleaning completed.

Creating smaller RAG chunks

I want to change our previous chunking approach.

Instead of 800 words, let's use approximately 350 words with 50-word overlap.

This is better for our RAG system because the retrieved context will be more focused.

In [38]:
def create_chunks(
    words,
    chunk_size=350,
    overlap=50
):

    chunks = []

    start = 0

    while start < len(words):

        end = min(
            start + chunk_size,
            len(words)
        )

        chunk_words = words[start:end]

        if len(chunk_words) >= 40:
            chunks.append(
                (start, end, chunk_words)
            )

        if end >= len(words):
            break

        start = end - overlap

    return chunks

Building the Final Corpus

In [39]:
corpus = []

chunk_id = 0

for chapter in chapter_ranges:

    records = [
        record
        for record in chapter_pages
        if record["chapter_number"]
        == chapter["chapter_number"]
    ]

    # Sort pages
    records = sorted(
        records,
        key=lambda x: x["pdf_page"]
    )

    # Process each page separately first
    # so we don't lose page information

    for record in records:

        words = record["text"].split()

        chunks = create_chunks(words)

        for chunk_number, (_, _, chunk_words) in enumerate(
            chunks,
            start=1
        ):

            chunk_text = " ".join(chunk_words)

            corpus.append({
                "id": f"chunk_{chunk_id}",
                "chapter_number": chapter["chapter_number"],
                "chapter": chapter["chapter"],
                "chunk_number": chunk_number,
                "pdf_page": record["pdf_page"],
                "printed_page": record["printed_page"],
                "text": chunk_text
            })

            chunk_id += 1

print("Total chunks:", len(corpus))

Total chunks: 307

In [40]:
# Converting to DataFrame 
corpus_df = pd.DataFrame(corpus)

print("Total chunks:", len(corpus_df))
print(
    "Total chapters:",
    corpus_df["chapter_number"].nunique()
)

display(corpus_df.head())

Total chunks: 307
Total chapters: 18

,id,chapter_number,chapter,chunk_number,pdf_page,printed_page,text
0,chunk_0,1,Crop Production and Management,1,14,1,CROP PRODUCTION AND MANAGEMENTCROP PRODUCTION ...
1,chunk_1,1,Crop Production and Management,1,15,2,SCIENCE2 variety of crops grown in different p...
2,chunk_2,1,Crop Production and Management,2,15,2,absorbed by plants. Since only a few centimetr...
3,chunk_3,1,Crop Production and Management,1,16,3,CROP PRODUCTION AND MANAGEMENT 3 turning and l...
4,chunk_4,1,Crop Production and Management,1,17,4,SCIENCE4 Activity 1.1 Take a beaker and fill h...

In [41]:
# Chapter Distribution 
chapter_distribution = (
    corpus_df
    .groupby(
        ["chapter_number", "chapter"]
    )
    .size()
    .reset_index(
        name="chunks"
    )
)

display(chapter_distribution)

    chapter_number                               chapter  chunks
0                1        Crop Production and Management      20
1                2        Microorganisms: Friend and Foe      18
2                3         Synthetic Fibres and Plastics      15
3                4      Materials: Metals and Non-Metals      16
4                5                    Coal and Petroleum       9
5                6                  Combustion and Flame      17
6                7    Conservation of Plants and Animals      15
7                8        Cell — Structure and Functions      13
8                9               Reproduction in Animals      16
9               10       Reaching the Age of Adolescence      20
10              11                    Force and Pressure      28
11              12                              Friction      13
12              13                                 Sound      16
13              14  Chemical Effects of Electric Current      18
14              15                Some Natural Phenomena      18
15              16                                 Light      23
16              17            Stars and the Solar System      30
17              18            Pollution of Air and Water       2

In [42]:
# Checking for Missing Chapters 
expected_chapters = set(range(1, 19))

actual_chapters = set(
    corpus_df["chapter_number"].unique()
)

missing_chapters = (
    expected_chapters - actual_chapters
)

if missing_chapters:
    print(
        "Missing chapters:",
        sorted(missing_chapters)
    )
else:
    print(
        "SUCCESS: All 18 chapters are present!"
    )

SUCCESS: All 18 chapters are present!

In [43]:
# Check the Chunk Size 
corpus_df["characters"] = (
    corpus_df["text"].str.len()
)

print(
    "Average characters:",
    round(
        corpus_df["characters"].mean(),
        2
    )
)

print(
    "Minimum characters:",
    corpus_df["characters"].min()
)

print(
    "Maximum characters:",
    corpus_df["characters"].max()
)

Average characters: 1393.49
Minimum characters: 268
Maximum characters: 2267

In [44]:
# Saving 

# Remove temporary column before saving
corpus_df = corpus_df.drop(
    columns=["characters"],
    errors="ignore"
)

with open(
    "class8_science.jsonl",
    "w",
    encoding="utf-8"
) as f:

    for record in corpus_df.to_dict(
        orient="records"
    ):

        f.write(
            json.dumps(
                record,
                ensure_ascii=False
            ) + "\n"
        )

print(
    "class8_science.jsonl created successfully!"
)

class8_science.jsonl created successfully!

Final Validation

In [45]:
print("=" * 55)
print("FINAL CORPUS VALIDATION")
print("=" * 55)

print(
    "Total chunks:",
    len(corpus_df)
)

print(
    "Total chapters:",
    corpus_df["chapter_number"].nunique()
)

print(
    "Unique chapters:",
    corpus_df["chapter"].nunique()
)

print(
    "Average chunk characters:",
    round(
        corpus_df["text"].str.len().mean(),
        2
    )
)

print(
    "Minimum chunk characters:",
    corpus_df["text"].str.len().min()
)

print(
    "Maximum chunk characters:",
    corpus_df["text"].str.len().max()
)

=======================================================
FINAL CORPUS VALIDATION
=======================================================
Total chunks: 307
Total chapters: 18
Unique chapters: 18
Average chunk characters: 1393.49
Minimum chunk characters: 268
Maximum chunk characters: 2267

In [46]:
from IPython.display import HTML, display

html = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <style>
        body {
            margin: 0;
            padding: 40px;
            background: #09090b;
            font-family: Arial, sans-serif;
            color: #f4f4f5;
        }

        .card {
            max-width: 850px;
            margin: auto;
            padding: 35px;
            background: linear-gradient(145deg, #18181b, #111113);
            border: 1px solid #27272a;
            border-radius: 18px;
            box-shadow: 0 15px 40px rgba(0, 0, 0, 0.5);
        }

        .badge {
            display: inline-block;
            padding: 7px 14px;
            margin-bottom: 20px;
            background: #27272a;
            color: #a1a1aa;
            border-radius: 20px;
            font-size: 13px;
            letter-spacing: 1px;
        }

        h2 {
            margin: 0;
            color: #ffffff;
            font-size: 25px;
            line-height: 1.5;
        }

        .line {
            width: 70px;
            height: 4px;
            margin: 22px 0;
            background: #8b5cf6;
            border-radius: 10px;
        }

        p {
            margin: 0;
            color: #d4d4d8;
            font-size: 18px;
            line-height: 1.8;
        }

        .highlight {
            color: #c4b5fd;
            font-weight: bold;
        }

        .icon {
            font-size: 25px;
            margin-right: 10px;
        }
    </style>
</head>

<body>

    <div class="card">

        <div class="badge">PROJECT STEP 02</div>

        <h2>
            <span class="icon">🧠</span>
            Part 2: Create Embeddings + FAISS/Haystack Index
        </h2>

        <div class="line"></div>

        <p>
            Create 
            <span class="highlight">embeddings</span>
            from the cleaned corpus and build a 
            <span class="highlight">FAISS/Haystack index</span>
            for efficient semantic search and retrieval.
        </p>

    </div>

</body>
</html>
"""

display(HTML(html))

In [47]:
# Installing the Liberaries for the Part 2 
!pip install -U sentence-transformers faiss-cpu haystack-ai

Requirement already satisfied: sentence-transformers in c:\users\hii\anaconda3\lib\site-packages (6.0.0)
Collecting sentence-transformers
  Downloading sentence_transformers-6.0.1-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: faiss-cpu in c:\users\hii\anaconda3\lib\site-packages (1.15.0)
Requirement already satisfied: haystack-ai in c:\users\hii\anaconda3\lib\site-packages (3.1.0)
Collecting haystack-ai
  Downloading haystack_ai-3.1.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: transformers<6.0.0,>=5.0.0 in c:\users\hii\anaconda3\lib\site-packages (from sentence-transformers) (5.16.1)
Requirement already satisfied: tokenizers>=0.19 in c:\users\hii\anaconda3\lib\site-packages (from sentence-transformers) (0.23.1)
Requirement already satisfied: huggingface-hub<2.0.0,>=1.3.0 in c:\users\hii\anaconda3\lib\site-packages (from sentence-transformers) (1.29.0)
Requirement already satisfied: torch>=2.2 in c:\users\hii\anaconda3\lib\site-packages (from sentence-transformers) (2.13.0)
Requirement already satisfied: numpy>=1.24.0 in c:\users\hii\anaconda3\lib\site-packages (from sentence-transformers) (2.3.5)
Requirement already satisfied: scikit-learn>=1.1.0 in c:\users\hii\anaconda3\lib\site-packages (from sentence-transformers) (1.7.2)
Requirement already satisfied: scipy>=1.0.0 in c:\users\hii\anaconda3\lib\site-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.10.0 in c:\users\hii\anaconda3\lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in c:\users\hii\anaconda3\lib\site-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: click<9.0.0,>=8.4.2 in c:\users\hii\anaconda3\lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in c:\users\hii\anaconda3\lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\hii\anaconda3\lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (2025.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in c:\users\hii\anaconda3\lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\hii\anaconda3\lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in c:\users\hii\anaconda3\lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\hii\anaconda3\lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (6.0.3)
Requirement already satisfied: anyio in c:\users\hii\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (4.10.0)
Requirement already satisfied: certifi in c:\users\hii\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\users\hii\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\hii\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (3.19)
Requirement already satisfied: h11>=0.16 in c:\users\hii\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.16.0)
Requirement already satisfied: regex>=2025.10.22 in c:\users\hii\anaconda3\lib\site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (2026.7.19)
Requirement already satisfied: typer in c:\users\hii\anaconda3\lib\site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (0.20.0)
Requirement already satisfied: safetensors>=0.8.0 in c:\users\hii\anaconda3\lib\site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (0.8.0)
Requirement already satisfied: docstring-parser in c:\users\hii\anaconda3\lib\site-packages (from haystack-ai) (0.18.0)
Requirement already satisfied: filetype in c:\users\hii\anaconda3\lib\site-packages (from haystack-ai) (1.2.0)
Requirement already satisfied: jinja2 in c:\users\hii\anaconda3\lib\site-packages (from haystack-ai) (3.1.6)
Requirement already satisfied: jsonschema in c:\users\hii\anaconda3\lib\site-packages (from haystack-ai) (4.25.0)
Requirement already satisfied: lazy-imports in c:\users\hii\anaconda3\lib\site-packages (from haystack-ai) (1.2.0)
Requirement already satisfied: markupsafe in c:\users\hii\anaconda3\lib\site-packages (from haystack-ai) (3.0.2)
Requirement already satisfied: more-itertools in c:\users\hii\anaconda3\lib\site-packages (from haystack-ai) (10.8.0)
Requirement already satisfied: networkx in c:\users\hii\anaconda3\lib\site-packages (from haystack-ai) (3.5)
Requirement already satisfied: openai>=2.6.0 in c:\users\hii\anaconda3\lib\site-packages (from haystack-ai) (3.6.0)
Requirement already satisfied: posthog!=3.12.0 in c:\users\hii\anaconda3\lib\site-packages (from haystack-ai) (7.44.2)
Requirement already satisfied: pydantic in c:\users\hii\anaconda3\lib\site-packages (from haystack-ai) (2.12.4)
Requirement already satisfied: python-dateutil in c:\users\hii\anaconda3\lib\site-packages (from haystack-ai) (2.9.0.post0)
Requirement already satisfied: tenacity!=8.4.0 in c:\users\hii\anaconda3\lib\site-packages (from haystack-ai) (9.1.2)
Requirement already satisfied: httpx2<3,>=2.7.0 in c:\users\hii\anaconda3\lib\site-packages (from openai>=2.6.0->haystack-ai) (2.12.0)
Requirement already satisfied: jiter<1,>=0.16.0 in c:\users\hii\anaconda3\lib\site-packages (from openai>=2.6.0->haystack-ai) (0.16.0)
Requirement already satisfied: sniffio in c:\users\hii\anaconda3\lib\site-packages (from openai>=2.6.0->haystack-ai) (1.3.0)
Requirement already satisfied: httpcore2==2.12.0 in c:\users\hii\anaconda3\lib\site-packages (from httpx2<3,>=2.7.0->openai>=2.6.0->haystack-ai) (2.12.0)
Requirement already satisfied: truststore>=0.10 in c:\users\hii\anaconda3\lib\site-packages (from httpx2<3,>=2.7.0->openai>=2.6.0->haystack-ai) (0.10.1)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\hii\anaconda3\lib\site-packages (from pydantic->haystack-ai) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\hii\anaconda3\lib\site-packages (from pydantic->haystack-ai) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\hii\anaconda3\lib\site-packages (from pydantic->haystack-ai) (0.4.2)
Requirement already satisfied: requests<3.0,>=2.7 in c:\users\hii\anaconda3\lib\site-packages (from posthog!=3.12.0->haystack-ai) (2.32.5)
Requirement already satisfied: backoff>=1.10.0 in c:\users\hii\anaconda3\lib\site-packages (from posthog!=3.12.0->haystack-ai) (2.2.1)
Requirement already satisfied: distro>=1.5.0 in c:\users\hii\anaconda3\lib\site-packages (from posthog!=3.12.0->haystack-ai) (1.9.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\hii\anaconda3\lib\site-packages (from requests<3.0,>=2.7->posthog!=3.12.0->haystack-ai) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hii\anaconda3\lib\site-packages (from requests<3.0,>=2.7->posthog!=3.12.0->haystack-ai) (2.5.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\hii\anaconda3\lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\hii\anaconda3\lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers) (3.5.0)
Requirement already satisfied: setuptools>=77.0.3 in c:\users\hii\anaconda3\lib\site-packages (from torch>=2.2->sentence-transformers) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\hii\anaconda3\lib\site-packages (from torch>=2.2->sentence-transformers) (1.14.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\hii\anaconda3\lib\site-packages (from sympy>=1.13.3->torch>=2.2->sentence-transformers) (1.3.0)
Requirement already satisfied: colorama in c:\users\hii\anaconda3\lib\site-packages (from tqdm>=4.0.0->sentence-transformers) (0.4.6)
Requirement already satisfied: attrs>=22.2.0 in c:\users\hii\anaconda3\lib\site-packages (from jsonschema->haystack-ai) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\hii\anaconda3\lib\site-packages (from jsonschema->haystack-ai) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\hii\anaconda3\lib\site-packages (from jsonschema->haystack-ai) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\hii\anaconda3\lib\site-packages (from jsonschema->haystack-ai) (0.28.0)
Requirement already satisfied: six>=1.5 in c:\users\hii\anaconda3\lib\site-packages (from python-dateutil->haystack-ai) (1.17.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\hii\anaconda3\lib\site-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\hii\anaconda3\lib\site-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (14.2.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\hii\anaconda3\lib\site-packages (from rich>=10.11.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\hii\anaconda3\lib\site-packages (from rich>=10.11.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\hii\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (0.1.2)
Downloading sentence_transformers-6.0.1-py3-none-any.whl (739 kB)
   ---------------------------------------- 0.0/739.8 kB ? eta -:--:--
   ---------------------------------------- 739.8/739.8 kB 5.3 MB/s  0:00:00
Downloading haystack_ai-3.1.1-py3-none-any.whl (713 kB)
   ---------------------------------------- 0.0/713.8 kB ? eta -:--:--
   ---------------------------------------- 713.8/713.8 kB 6.6 MB/s  0:00:00
Installing collected packages: haystack-ai, sentence-transformers

  Attempting uninstall: haystack-ai

    Found existing installation: haystack-ai 3.1.0

   ---------------------------------------- 0/2 [haystack-ai]
   ---------------------------------------- 0/2 [haystack-ai]
   ---------------------------------------- 0/2 [haystack-ai]
    Uninstalling haystack-ai-3.1.0:
   ---------------------------------------- 0/2 [haystack-ai]
      Successfully uninstalled haystack-ai-3.1.0
   ---------------------------------------- 0/2 [haystack-ai]
   ---------------------------------------- 0/2 [haystack-ai]
   ---------------------------------------- 0/2 [haystack-ai]
   ---------------------------------------- 0/2 [haystack-ai]
   ---------------------------------------- 0/2 [haystack-ai]
   ---------------------------------------- 0/2 [haystack-ai]
   ---------------------------------------- 0/2 [haystack-ai]
   ---------------------------------------- 0/2 [haystack-ai]
   ---------------------------------------- 0/2 [haystack-ai]
   ---------------------------------------- 0/2 [haystack-ai]
   ---------------------------------------- 0/2 [haystack-ai]
   ---------------------------------------- 0/2 [haystack-ai]
   ---------------------------------------- 0/2 [haystack-ai]
   ---------------------------------------- 0/2 [haystack-ai]
   ---------------------------------------- 0/2 [haystack-ai]
   ---------------------------------------- 0/2 [haystack-ai]
   ---------------------------------------- 0/2 [haystack-ai]
   ---------------------------------------- 0/2 [haystack-ai]
   ---------------------------------------- 0/2 [haystack-ai]
   ---------------------------------------- 0/2 [haystack-ai]
   ---------------------------------------- 0/2 [haystack-ai]
   ---------------------------------------- 0/2 [haystack-ai]
   ---------------------------------------- 0/2 [haystack-ai]
   ---------------------------------------- 0/2 [haystack-ai]
   ---------------------------------------- 0/2 [haystack-ai]
  Attempting uninstall: sentence-transformers
   ---------------------------------------- 0/2 [haystack-ai]
    Found existing installation: sentence-transformers 6.0.0
   ---------------------------------------- 0/2 [haystack-ai]
   -------------------- ------------------- 1/2 [sentence-transformers]
   -------------------- ------------------- 1/2 [sentence-transformers]
   -------------------- ------------------- 1/2 [sentence-transformers]
    Uninstalling sentence-transformers-6.0.0:
   -------------------- ------------------- 1/2 [sentence-transformers]
      Successfully uninstalled sentence-transformers-6.0.0
   -------------------- ------------------- 1/2 [sentence-transformers]
   -------------------- ------------------- 1/2 [sentence-transformers]
   -------------------- ------------------- 1/2 [sentence-transformers]
   -------------------- ------------------- 1/2 [sentence-transformers]
   -------------------- ------------------- 1/2 [sentence-transformers]
   -------------------- ------------------- 1/2 [sentence-transformers]
   -------------------- ------------------- 1/2 [sentence-transformers]
   -------------------- ------------------- 1/2 [sentence-transformers]
   -------------------- ------------------- 1/2 [sentence-transformers]
   -------------------- ------------------- 1/2 [sentence-transformers]
   -------------------- ------------------- 1/2 [sentence-transformers]
   -------------------- ------------------- 1/2 [sentence-transformers]
   -------------------- ------------------- 1/2 [sentence-transformers]
   -------------------- ------------------- 1/2 [sentence-transformers]
   -------------------- ------------------- 1/2 [sentence-transformers]
   -------------------- ------------------- 1/2 [sentence-transformers]
   -------------------- ------------------- 1/2 [sentence-transformers]
   -------------------- ------------------- 1/2 [sentence-transformers]
   -------------------- ------------------- 1/2 [sentence-transformers]
   ---------------------------------------- 2/2 [sentence-transformers]

Successfully installed haystack-ai-3.1.1 sentence-transformers-6.0.1

In [48]:
import json
import os

import numpy as np
import pandas as pd

from sentence_transformers import SentenceTransformer
import faiss

from haystack import Document

In [49]:
# Load our JSONL Corpus 
corpus_file = "class8_science.jsonl"

documents = []

with open(corpus_file, "r", encoding="utf-8") as f:
    for line in f:
        documents.append(json.loads(line))

print("Total documents:", len(documents))

Total documents: 307

In [50]:
# Load the Embedding Model 

model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

print("Embedding model loaded successfully.")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Embedding model loaded successfully.

In [51]:
# Prepare the Texts 

texts = [
    document["text"]
    for document in documents
]

print("Number of texts:", len(texts))

Number of texts: 307

In [52]:
# Generating the Embeddings 

embeddings = model.encode(
    texts,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True
)

print("Embeddings generated.")
print("Embedding shape:", embeddings.shape)

Batches:   0%|          | 0/10 [00:00<?, ?it/s]

Embeddings generated.
Embedding shape: (307, 384)

In [53]:
# Verifying the Embeddings 
print("Data type:", embeddings.dtype)
print("Number of vectors:", len(embeddings))
print("Vector dimensions:", embeddings.shape[1])

Data type: float32
Number of vectors: 307
Vector dimensions: 384

In [54]:
# Creating the FAISS Index 
dimension = embeddings.shape[1]

index = faiss.IndexFlatIP(dimension)

index.add(
    embeddings.astype("float32")
)

print("FAISS index created.")
print("Number of vectors in index:", index.ntotal)

FAISS index created.
Number of vectors in index: 307

In [55]:
# Saving 
os.makedirs("vector_store", exist_ok=True)

In [56]:
faiss.write_index(
    index,
    "vector_store/class8_science.faiss"
)

print("FAISS index saved successfully.")

FAISS index saved successfully.

In [57]:
# Save the Document Metadata 
with open(
    "vector_store/documents.json",
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        documents,
        f,
        ensure_ascii=False,
        indent=2
    )

print("Document metadata saved.")

Document metadata saved.

In [58]:
# Create a Semantic Search Function 
def semantic_search(
    query,
    top_k=5
):

    # Convert question to embedding
    query_embedding = model.encode(
        [query],
        convert_to_numpy=True,
        normalize_embeddings=True
    ).astype("float32")

    # Search FAISS
    scores, indices = index.search(
        query_embedding,
        top_k
    )

    results = []

    for score, idx in zip(
        scores[0],
        indices[0]
    ):

        result = documents[idx].copy()

        result["similarity_score"] = float(score)

        results.append(result)

    return results

In [59]:
# Teasting the Semantic Search 
query = "What is photosynthesis?"

results = semantic_search(
    query,
    top_k=5
)

for i, result in enumerate(results, start=1):

    print("=" * 70)
    print(f"Result {i}")
    print("Chapter:", result["chapter"])
    print("Page:", result["printed_page"])
    print(
        "Similarity:",
        round(result["similarity_score"], 4)
    )
    print("Text:")
    print(result["text"][:700])

======================================================================
Result 1
Chapter: Cell — Structure and Functions
Page: 96
Similarity: 0.4087
Text:
SCIENCE96 While observing the onion cells under the microscope, did you notice any blank-looking structures in the cytoplasm? It is called vacuole. It could be single and big as in an onion cell. Cheek cells have smaller vacuoles. Large vacuoles are common in plant cells. Vacuoles in animal cells ar e much smaller. You might have noticed several small coloured bodies in the cytoplasm of the cells of Tradescantia leaf. They ar e scattered in the cytoplasm of the leaf cells. These are called plastids. They are of different colours. Some of them contain green pigment called chlorophyll. Green coloured plastids are called chloroplasts. They provide green colour to the leaves. You may recall that
======================================================================
Result 2
Chapter: Microorganisms: Friend and Foe
Page: 27
Similarity: 0.3687
Text:
MICROORGANISMS: FRIEND AND FOE 27 nitrogen cannot be taken directly by plants and animals. Certain bacteria and blue green algae present in the soil fix nitrogen from the atmosphere and convert it into compounds of nitrogen. Once nitrogen is converted into these usable compounds, it can be utilised by plants from the soil through their root system. Nitrogen is then used for the synthesis of plant proteins and other compounds. Animals feeding on plants get these proteins and other nitrogen compounds (Fig. 2.10). When plants and animals die, bacteria and fungi present in the soil convert the nitrogenous wastes into nitrogenous compounds to be used by plants again. Certain other bacteria conver
======================================================================
Result 3
Chapter: Crop Production and Management
Page: 6
Similarity: 0.3477
Text:
are being encouraged to adopt this practice. In the previous classes, you have learnt about Rhizobium bacteria. These are present in the nodules of roots of leguminous plants. They fix atmospheric nitrogen. Fig. 1.3 (a): Preparation of the experiment Did plants in all the glasses grow at the same pace? Which glass showed Fig. 1.3 (b): Growing seedlings with manure and fertiliser
======================================================================
Result 4
Chapter: Coal and Petroleum
Page: 57
Similarity: 0.3387
Text:
million years ago the earth had dense forests in low lying wetland areas. Due to natural processes, like flooding, these forests got buried under the soil. As more soil deposited over them, they were compressed. The temperature also rose as they sank deeper and deeper. Under high pressure and high temperature, dead plants got slowly converted to coal. As coal contains mainly carbon, the slow process of conversion of dead vegetation into coal is called carbonisation. Since it was formed from the remains of vegetation, coal is also called a fossil fuel. A coal mine is shown in Fig. 5.2. COAL AND PETROLEUM 57
======================================================================
Result 5
Chapter: Cell — Structure and Functions
Page: 95
Similarity: 0.2964
Text:
structure of the nucleus is the same in cells of plants, animals and bacteria. The nucleus of the bacterial cell is not well-organised like the cells of multicellular organisms. There is no nuclear membrane. The cells having nuclear material without nuclear membrane are termed prokaryotic cells. The organisms with these kinds of cells are called prokaryotes (pro: primitive; karyon: nucleus). Examples are bacteria and blue green algae. The cells, like onion cells and cheek cells having well-organised nucleus with a nuclear membrane are designated as eukaryotic cells. All organisms other than bacteria and blue green algae are called eukaryotes. (eu: true; karyon: nucleus). cell membrane nucleu

In [60]:
# Another Question 
query = "Why do we use manure and fertilisers?"

results = semantic_search(
    query,
    top_k=5
)

for i, result in enumerate(results, start=1):

    print("=" * 70)
    print(f"Result {i}")
    print("Chapter:", result["chapter"])
    print("Page:", result["printed_page"])
    print(
        "Similarity:",
        round(result["similarity_score"], 4)
    )
    print(result["text"][:500])

======================================================================
Result 1
Chapter: Crop Production and Management
Page: 7
Similarity: 0.6212
CROP PRODUCTION AND MANAGEMENT 7 Table 1.1 gives the differences between a fertili ser and manure. Advantages of Manure: The organic manure is considered better than fertilisers. This is because /circle6it enhances the water holding capacity of the soil. /circle6it makes the soil porous due to which exchange of gases becomes easy. /circle6it increases the number of friendly microbes. /circle6it improves the texture of the soil. 1.6 Irrigation All living beings need water to live. Water is import
======================================================================
Result 2
Chapter: Crop Production and Management
Page: 5
Similarity: 0.6067
weak plants. Manure is an organic substance obtained from the decomposition of plant or animal wastes. Farmers dump plant and animal waste in pits at open places and allow it to decompose. The decomposition is caused by some microorganisms. The decomposed matter is used as organic manure. You have alr eady lear nt about vermicomposting in Class VI.
======================================================================
Result 3
Chapter: Crop Production and Management
Page: 3
Similarity: 0.5219
CROP PRODUCTION AND MANAGEMENT 3 turning and loosening of soil is very important for cultivation of crops. The process of loosening and turning of the soil is called tilling or ploughing. This is done by using a plough. Ploughs are made of wood or iron. If the soil is very dry, it may need watering before ploughing. The ploughed field may have big clumps of soil called crumbs. It is necessary to break these crumbs. Levelling the field is beneficial for sowing as well as for irrigation. Levelling
======================================================================
Result 4
Chapter: Crop Production and Management
Page: 5
Similarity: 0.4934
CROP PRODUCTION AND MANAGEMENT 5 Seed drill: Nowadays the seed drill [Fig. 1.2 (b)] is used for sowing with the help of tractors. This sows the seeds uniformly at equal distance and depth. It ensures that seeds get covered by the soil after sowing. This protects seeds from being eaten by birds. Sowing by using a seed drill saves time and labour. Fig. 1.2 (b): A seed drill There is a nursery near my school. I found that little plants were kept in small bags. Why are they kept like this? Seeds of
======================================================================
Result 5
Chapter: Crop Production and Management
Page: 9
Similarity: 0.4744
CROP PRODUCTION AND MANAGEMENT 9 Modern Methods of Irrigation Modern methods of irrigation help us to use water economically. The main methods used are as follows: (i) Sprinkler System: This system is more useful on the uneven land where sufficient water is not available. The perpendicular pipes, having rotating nozzles on top, are joined to the main pipeline at regular intervals. When water is allowed to flow through the main pipe under pressure with the help of a pump, it escapes from the rota

In [61]:
# Testing an out of syllabus Question 
query = "Who was the first Prime Minister of India?"

results = semantic_search(
    query,
    top_k=5
)

for i, result in enumerate(results, start=1):

    print("=" * 70)
    print(f"Result {i}")
    print("Chapter:", result["chapter"])
    print(
        "Similarity:",
        round(result["similarity_score"], 4)
    )

======================================================================
Result 1
Chapter: Stars and the Solar System
Similarity: 0.2627
======================================================================
Result 2
Chapter: Stars and the Solar System
Similarity: 0.2568
======================================================================
Result 3
Chapter: Crop Production and Management
Similarity: 0.2427
======================================================================
Result 4
Chapter: Crop Production and Management
Similarity: 0.2404
======================================================================
Result 5
Chapter: Stars and the Solar System
Similarity: 0.2336

In [62]:
# Convert our corpus into Haystack Documents 
haystack_documents = []

for document in documents:

    haystack_doc = Document(
        content=document["text"],
        meta={
            "id": document["id"],
            "chapter_number": document["chapter_number"],
            "chapter": document["chapter"],
            "chunk_number": document["chunk_number"],
            "pdf_page": document["pdf_page"],
            "printed_page": document["printed_page"]
        }
    )

    haystack_documents.append(
        haystack_doc
    )

print(
    "Haystack documents:",
    len(haystack_documents)
)

Haystack documents: 307

In [63]:
# Verify a Haystack Document 
haystack_documents[0]

Document(id=83de09ad973989a37eca15add153661afe3f1cc535395c55e24ff48500e926a7, content: 'CROP PRODUCTION AND MANAGEMENTCROP PRODUCTION AND MANAGEMENT P aheli and Boojho went to their uncle’...', meta: {'id': 'chunk_0', 'chapter_number': 1, 'chapter': 'Crop Production and Management', 'chunk_number': 1, 'pdf_page': 14, 'printed_page': 1})

In [64]:
from haystack.document_stores.in_memory import InMemoryDocumentStore

document_store = InMemoryDocumentStore()

print("Haystack document store created.")

Haystack document store created.

In [65]:
document_store.write_documents(
    haystack_documents
)

print(
    "Documents stored:",
    document_store.count_documents()
)

Documents stored: 307

In [66]:
print("=" * 60)
print("PART 2 COMPLETE")
print("=" * 60)

print("Corpus documents:", len(documents))
print("Embedding dimensions:", embeddings.shape[1])
print("FAISS vectors:", index.ntotal)
print(
    "Haystack documents:",
    document_store.count_documents()
)

============================================================
PART 2 COMPLETE
============================================================
Corpus documents: 307
Embedding dimensions: 384
FAISS vectors: 307
Haystack documents: 307

In [67]:
from IPython.display import HTML, display

html = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <style>
        body {
            margin: 0;
            padding: 40px;
            background: #09090b;
            font-family: Arial, sans-serif;
            color: #f4f4f5;
        }

        .card {
            max-width: 850px;
            margin: auto;
            padding: 35px;
            background: linear-gradient(145deg, #18181b, #111113);
            border: 1px solid #27272a;
            border-radius: 18px;
            box-shadow: 0 15px 40px rgba(0, 0, 0, 0.5);
        }

        .badge {
            display: inline-block;
            padding: 7px 14px;
            margin-bottom: 20px;
            background: #27272a;
            color: #a1a1aa;
            border-radius: 20px;
            font-size: 13px;
            letter-spacing: 1px;
        }

        h2 {
            margin: 0;
            color: #ffffff;
            font-size: 25px;
            line-height: 1.5;
        }

        .line {
            width: 70px;
            height: 4px;
            margin: 22px 0;
            background: #8b5cf6;
            border-radius: 10px;
        }

        p {
            margin: 0;
            color: #d4d4d8;
            font-size: 18px;
            line-height: 1.8;
        }

        .highlight {
            color: #c4b5fd;
            font-weight: bold;
        }

        .icon {
            font-size: 25px;
            margin-right: 10px;
        }
    </style>
</head>

<body>

    <div class="card">

        <div class="badge">PROJECT STEP 03</div>

        <h2>
            <span class="icon">🔗</span>
            Part 3: Build the RAG Pipeline and Textbook-Only Prompt
        </h2>

        <div class="line"></div>

        <p>
            Build the 
            <span class="highlight">RAG pipeline</span>
            and create a 
            <span class="highlight">textbook-only prompt</span>
            to ensure that responses are generated using information retrieved from the NCERT textbook.
        </p>

    </div>

</body>
</html>
"""

display(HTML(html))

In [68]:
# Install teh LLM Liberaries 
!pip install -U transformers torch sentencepiece

Requirement already satisfied: transformers in c:\users\hii\anaconda3\lib\site-packages (5.16.1)
Requirement already satisfied: torch in c:\users\hii\anaconda3\lib\site-packages (2.13.0)
Collecting torch
  Downloading torch-2.14.0-cp313-cp313-win_amd64.whl.metadata (38 kB)
Requirement already satisfied: sentencepiece in c:\users\hii\anaconda3\lib\site-packages (0.2.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\hii\anaconda3\lib\site-packages (from transformers) (1.29.0)
Requirement already satisfied: numpy>=1.17 in c:\users\hii\anaconda3\lib\site-packages (from transformers) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\users\hii\anaconda3\lib\site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\hii\anaconda3\lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in c:\users\hii\anaconda3\lib\site-packages (from transformers) (2026.7.19)
Requirement already satisfied: tokenizers<0.24.0,>=0.23.1 in c:\users\hii\anaconda3\lib\site-packages (from transformers) (0.23.1)
Requirement already satisfied: typer in c:\users\hii\anaconda3\lib\site-packages (from transformers) (0.20.0)
Requirement already satisfied: safetensors>=0.8.0 in c:\users\hii\anaconda3\lib\site-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in c:\users\hii\anaconda3\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: click<9.0.0,>=8.4.2 in c:\users\hii\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in c:\users\hii\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\hii\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in c:\users\hii\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\hii\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\hii\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in c:\users\hii\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.10.0)
Requirement already satisfied: certifi in c:\users\hii\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\users\hii\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\hii\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.19)
Requirement already satisfied: h11>=0.16 in c:\users\hii\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: setuptools>=77.0.3 in c:\users\hii\anaconda3\lib\site-packages (from torch) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\hii\anaconda3\lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\hii\anaconda3\lib\site-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in c:\users\hii\anaconda3\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\hii\anaconda3\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: colorama in c:\users\hii\anaconda3\lib\site-packages (from tqdm>=4.60->transformers) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in c:\users\hii\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\hii\anaconda3\lib\site-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\hii\anaconda3\lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\hii\anaconda3\lib\site-packages (from typer->transformers) (14.2.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\hii\anaconda3\lib\site-packages (from rich>=10.11.0->typer->transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\hii\anaconda3\lib\site-packages (from rich>=10.11.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\hii\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->transformers) (0.1.2)
Downloading torch-2.14.0-cp313-cp313-win_amd64.whl (124.1 MB)
   ---------------------------------------- 0.0/124.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/124.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/124.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/124.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/124.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/124.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/124.1 MB ? eta -:--:--
   ---------------------------------------- 0.8/124.1 MB 1.2 MB/s eta 0:01:43
   ---------------------------------------- 1.3/124.1 MB 1.7 MB/s eta 0:01:14
    --------------------------------------- 2.1/124.1 MB 2.1 MB/s eta 0:00:59
    --------------------------------------- 2.9/124.1 MB 2.4 MB/s eta 0:00:51
   - -------------------------------------- 3.7/124.1 MB 2.5 MB/s eta 0:00:48
   - -------------------------------------- 4.2/124.1 MB 2.6 MB/s eta 0:00:46
   - -------------------------------------- 5.0/124.1 MB 2.7 MB/s eta 0:00:44
   - -------------------------------------- 5.5/124.1 MB 2.6 MB/s eta 0:00:46
   - -------------------------------------- 6.0/124.1 MB 2.6 MB/s eta 0:00:46
   -- ------------------------------------- 6.3/124.1 MB 2.5 MB/s eta 0:00:47
   -- ------------------------------------- 7.1/124.1 MB 2.6 MB/s eta 0:00:45
   -- ------------------------------------- 7.6/124.1 MB 2.6 MB/s eta 0:00:45
   -- ------------------------------------- 8.4/124.1 MB 2.7 MB/s eta 0:00:44
   -- ------------------------------------- 8.4/124.1 MB 2.7 MB/s eta 0:00:44
   -- ------------------------------------- 8.9/124.1 MB 2.5 MB/s eta 0:00:47
   --- ------------------------------------ 9.4/124.1 MB 2.5 MB/s eta 0:00:47
   --- ------------------------------------ 10.0/124.1 MB 2.5 MB/s eta 0:00:46
   --- ------------------------------------ 10.5/124.1 MB 2.5 MB/s eta 0:00:45
   --- ------------------------------------ 11.3/124.1 MB 2.6 MB/s eta 0:00:45
   --- ------------------------------------ 11.8/124.1 MB 2.6 MB/s eta 0:00:44
   --- ------------------------------------ 12.3/124.1 MB 2.5 MB/s eta 0:00:44
   ---- ----------------------------------- 12.6/124.1 MB 2.5 MB/s eta 0:00:45
   ---- ----------------------------------- 13.4/124.1 MB 2.5 MB/s eta 0:00:44
   ---- ----------------------------------- 13.9/124.1 MB 2.5 MB/s eta 0:00:44
   ---- ----------------------------------- 14.9/124.1 MB 2.6 MB/s eta 0:00:42
   ----- ---------------------------------- 16.0/124.1 MB 2.7 MB/s eta 0:00:40
   ----- ---------------------------------- 17.0/124.1 MB 2.8 MB/s eta 0:00:39
   ----- ---------------------------------- 17.8/124.1 MB 2.8 MB/s eta 0:00:38
   ------ --------------------------------- 18.9/124.1 MB 2.9 MB/s eta 0:00:37
   ------ --------------------------------- 19.9/124.1 MB 3.0 MB/s eta 0:00:36
   ------ --------------------------------- 20.7/124.1 MB 3.0 MB/s eta 0:00:35
   ------ --------------------------------- 21.5/124.1 MB 3.0 MB/s eta 0:00:35
   ------- -------------------------------- 22.0/124.1 MB 3.0 MB/s eta 0:00:35
   ------- -------------------------------- 22.8/124.1 MB 3.0 MB/s eta 0:00:34
   ------- -------------------------------- 23.9/124.1 MB 3.1 MB/s eta 0:00:33
   -------- ------------------------------- 24.9/124.1 MB 3.1 MB/s eta 0:00:32
   -------- ------------------------------- 25.7/124.1 MB 3.2 MB/s eta 0:00:32
   -------- ------------------------------- 27.0/124.1 MB 3.2 MB/s eta 0:00:31
   --------- ------------------------------ 28.0/124.1 MB 3.3 MB/s eta 0:00:30
   --------- ------------------------------ 29.1/124.1 MB 3.3 MB/s eta 0:00:29
   --------- ------------------------------ 30.1/124.1 MB 3.3 MB/s eta 0:00:29
   ---------- ----------------------------- 31.2/124.1 MB 3.4 MB/s eta 0:00:28
   ---------- ----------------------------- 32.5/124.1 MB 3.4 MB/s eta 0:00:27
   ---------- ----------------------------- 33.6/124.1 MB 3.5 MB/s eta 0:00:27
   ----------- ---------------------------- 34.3/124.1 MB 3.5 MB/s eta 0:00:26
   ----------- ---------------------------- 35.4/124.1 MB 3.5 MB/s eta 0:00:26
   ----------- ---------------------------- 36.7/124.1 MB 3.6 MB/s eta 0:00:25
   ------------ --------------------------- 37.7/124.1 MB 3.6 MB/s eta 0:00:24
   ------------ --------------------------- 38.5/124.1 MB 3.6 MB/s eta 0:00:24
   ------------ --------------------------- 39.3/124.1 MB 3.6 MB/s eta 0:00:24
   ------------- -------------------------- 40.4/124.1 MB 3.6 MB/s eta 0:00:24
   ------------- -------------------------- 41.2/124.1 MB 3.6 MB/s eta 0:00:23
   ------------- -------------------------- 42.2/124.1 MB 3.6 MB/s eta 0:00:23
   ------------- -------------------------- 43.3/124.1 MB 3.7 MB/s eta 0:00:23
   -------------- ------------------------- 44.3/124.1 MB 3.7 MB/s eta 0:00:22
   -------------- ------------------------- 45.1/124.1 MB 3.7 MB/s eta 0:00:22
   -------------- ------------------------- 46.1/124.1 MB 3.7 MB/s eta 0:00:22
   --------------- ------------------------ 46.9/124.1 MB 3.7 MB/s eta 0:00:21
   --------------- ------------------------ 47.4/124.1 MB 3.7 MB/s eta 0:00:21
   --------------- ------------------------ 48.2/124.1 MB 3.7 MB/s eta 0:00:21
   --------------- ------------------------ 49.3/124.1 MB 3.7 MB/s eta 0:00:21
   ---------------- ----------------------- 50.1/124.1 MB 3.7 MB/s eta 0:00:20
   ---------------- ----------------------- 50.9/124.1 MB 3.7 MB/s eta 0:00:20
   ---------------- ----------------------- 51.9/124.1 MB 3.7 MB/s eta 0:00:20
   ---------------- ----------------------- 52.2/124.1 MB 3.7 MB/s eta 0:00:20
   ----------------- ---------------------- 53.2/124.1 MB 3.7 MB/s eta 0:00:20
   ----------------- ---------------------- 54.0/124.1 MB 3.7 MB/s eta 0:00:19
   ----------------- ---------------------- 55.1/124.1 MB 3.7 MB/s eta 0:00:19
   ------------------ --------------------- 56.1/124.1 MB 3.7 MB/s eta 0:00:19
   ------------------ --------------------- 57.1/124.1 MB 3.7 MB/s eta 0:00:18
   ------------------ --------------------- 58.2/124.1 MB 3.8 MB/s eta 0:00:18
   ------------------- -------------------- 59.0/124.1 MB 3.8 MB/s eta 0:00:18
   ------------------- -------------------- 60.0/124.1 MB 3.8 MB/s eta 0:00:17
   ------------------- -------------------- 60.8/124.1 MB 3.8 MB/s eta 0:00:17
   ------------------- -------------------- 61.9/124.1 MB 3.8 MB/s eta 0:00:17
   -------------------- ------------------- 62.7/124.1 MB 3.8 MB/s eta 0:00:17
   -------------------- ------------------- 63.4/124.1 MB 3.8 MB/s eta 0:00:16
   -------------------- ------------------- 64.5/124.1 MB 3.8 MB/s eta 0:00:16
   --------------------- ------------------ 65.3/124.1 MB 3.8 MB/s eta 0:00:16
   --------------------- ------------------ 65.8/124.1 MB 3.8 MB/s eta 0:00:16
   --------------------- ------------------ 66.1/124.1 MB 3.7 MB/s eta 0:00:16
   --------------------- ------------------ 66.3/124.1 MB 3.7 MB/s eta 0:00:16
   --------------------- ------------------ 67.4/124.1 MB 3.7 MB/s eta 0:00:16
   ---------------------- ----------------- 68.4/124.1 MB 3.8 MB/s eta 0:00:15
   ---------------------- ----------------- 69.5/124.1 MB 3.8 MB/s eta 0:00:15
   ---------------------- ----------------- 70.5/124.1 MB 3.8 MB/s eta 0:00:15
   ----------------------- ---------------- 71.6/124.1 MB 3.8 MB/s eta 0:00:14
   ----------------------- ---------------- 72.6/124.1 MB 3.8 MB/s eta 0:00:14
   ----------------------- ---------------- 72.9/124.1 MB 3.8 MB/s eta 0:00:14
   ----------------------- ---------------- 73.9/124.1 MB 3.8 MB/s eta 0:00:14
   ------------------------ --------------- 75.0/124.1 MB 3.8 MB/s eta 0:00:13
   ------------------------ --------------- 75.8/124.1 MB 3.8 MB/s eta 0:00:13
   ------------------------ --------------- 76.8/124.1 MB 3.8 MB/s eta 0:00:13
   ------------------------ --------------- 77.3/124.1 MB 3.8 MB/s eta 0:00:13
   ------------------------- -------------- 78.1/124.1 MB 3.8 MB/s eta 0:00:13
   ------------------------- -------------- 79.2/124.1 MB 3.8 MB/s eta 0:00:12
   ------------------------- -------------- 80.2/124.1 MB 3.8 MB/s eta 0:00:12
   -------------------------- ------------- 81.3/124.1 MB 3.8 MB/s eta 0:00:12
   -------------------------- ------------- 82.6/124.1 MB 3.8 MB/s eta 0:00:11
   -------------------------- ------------- 83.6/124.1 MB 3.9 MB/s eta 0:00:11
   --------------------------- ------------ 84.7/124.1 MB 3.9 MB/s eta 0:00:11
   --------------------------- ------------ 86.0/124.1 MB 3.9 MB/s eta 0:00:10
   --------------------------- ------------ 86.5/124.1 MB 3.9 MB/s eta 0:00:10
   ---------------------------- ----------- 87.3/124.1 MB 3.9 MB/s eta 0:00:10
   ---------------------------- ----------- 88.1/124.1 MB 3.9 MB/s eta 0:00:10
   ---------------------------- ----------- 89.4/124.1 MB 3.9 MB/s eta 0:00:09
   ----------------------------- ---------- 90.7/124.1 MB 3.9 MB/s eta 0:00:09
   ----------------------------- ---------- 92.0/124.1 MB 3.9 MB/s eta 0:00:09
   ------------------------------ --------- 93.3/124.1 MB 4.0 MB/s eta 0:00:08
   ------------------------------ --------- 94.1/124.1 MB 4.0 MB/s eta 0:00:08
   ------------------------------ --------- 95.4/124.1 MB 4.0 MB/s eta 0:00:08
   ------------------------------- -------- 96.5/124.1 MB 4.0 MB/s eta 0:00:07
   ------------------------------- -------- 97.3/124.1 MB 4.0 MB/s eta 0:00:07
   ------------------------------- -------- 97.5/124.1 MB 4.0 MB/s eta 0:00:07
   ------------------------------- -------- 97.8/124.1 MB 3.9 MB/s eta 0:00:07
   ------------------------------- -------- 98.6/124.1 MB 3.9 MB/s eta 0:00:07
   ------------------------------- -------- 99.1/124.1 MB 3.9 MB/s eta 0:00:07
   -------------------------------- ------- 99.9/124.1 MB 3.9 MB/s eta 0:00:07
   -------------------------------- ------- 100.7/124.1 MB 3.9 MB/s eta 0:00:06
   -------------------------------- ------- 101.2/124.1 MB 3.9 MB/s eta 0:00:06
   -------------------------------- ------- 102.0/124.1 MB 3.9 MB/s eta 0:00:06
   --------------------------------- ------ 102.8/124.1 MB 3.9 MB/s eta 0:00:06
   --------------------------------- ------ 103.3/124.1 MB 3.9 MB/s eta 0:00:06
   --------------------------------- ------ 104.1/124.1 MB 3.9 MB/s eta 0:00:06
   --------------------------------- ------ 105.1/124.1 MB 3.9 MB/s eta 0:00:05
   ---------------------------------- ----- 105.6/124.1 MB 3.9 MB/s eta 0:00:05
   ---------------------------------- ----- 106.2/124.1 MB 3.9 MB/s eta 0:00:05
   ---------------------------------- ----- 106.7/124.1 MB 3.9 MB/s eta 0:00:05
   ---------------------------------- ----- 107.0/124.1 MB 3.8 MB/s eta 0:00:05
   ---------------------------------- ----- 107.2/124.1 MB 3.8 MB/s eta 0:00:05
   ---------------------------------- ----- 107.7/124.1 MB 3.8 MB/s eta 0:00:05
   ---------------------------------- ----- 108.3/124.1 MB 3.8 MB/s eta 0:00:05
   ----------------------------------- ---- 109.1/124.1 MB 3.8 MB/s eta 0:00:04
   ----------------------------------- ---- 109.8/124.1 MB 3.8 MB/s eta 0:00:04
   ----------------------------------- ---- 110.4/124.1 MB 3.8 MB/s eta 0:00:04
   ----------------------------------- ---- 110.9/124.1 MB 3.8 MB/s eta 0:00:04
   ----------------------------------- ---- 111.7/124.1 MB 3.8 MB/s eta 0:00:04
   ------------------------------------ --- 112.5/124.1 MB 3.8 MB/s eta 0:00:04
   ------------------------------------ --- 113.2/124.1 MB 3.8 MB/s eta 0:00:03
   ------------------------------------ --- 113.8/124.1 MB 3.8 MB/s eta 0:00:03
   ------------------------------------ --- 114.6/124.1 MB 3.8 MB/s eta 0:00:03
   ------------------------------------- -- 115.3/124.1 MB 3.8 MB/s eta 0:00:03
   ------------------------------------- -- 116.1/124.1 MB 3.8 MB/s eta 0:00:03
   ------------------------------------- -- 116.9/124.1 MB 3.8 MB/s eta 0:00:02
   -------------------------------------- - 118.0/124.1 MB 3.8 MB/s eta 0:00:02
   -------------------------------------- - 118.5/124.1 MB 3.8 MB/s eta 0:00:02
   -------------------------------------- - 118.8/124.1 MB 3.8 MB/s eta 0:00:02
   -------------------------------------- - 118.8/124.1 MB 3.8 MB/s eta 0:00:02
   -------------------------------------- - 119.0/124.1 MB 3.8 MB/s eta 0:00:02
   -------------------------------------- - 119.3/124.1 MB 3.8 MB/s eta 0:00:02
   -------------------------------------- - 119.5/124.1 MB 3.8 MB/s eta 0:00:02
   -------------------------------------- - 119.5/124.1 MB 3.8 MB/s eta 0:00:02
   -------------------------------------- - 119.8/124.1 MB 3.7 MB/s eta 0:00:02
   -------------------------------------- - 119.8/124.1 MB 3.7 MB/s eta 0:00:02
   -------------------------------------- - 120.1/124.1 MB 3.7 MB/s eta 0:00:02
   -------------------------------------- - 120.3/124.1 MB 3.7 MB/s eta 0:00:02
   ---------------------------------------  121.1/124.1 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  122.2/124.1 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  122.9/124.1 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  123.5/124.1 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  124.0/124.1 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------  124.0/124.1 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------  124.0/124.1 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------  124.0/124.1 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------  124.0/124.1 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------  124.0/124.1 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------- 124.1/124.1 MB 3.6 MB/s  0:00:36
Installing collected packages: torch
  Attempting uninstall: torch
    Found existing installation: torch 2.13.0
    Uninstalling torch-2.13.0:
      Successfully uninstalled torch-2.13.0
Successfully installed torch-2.14.0

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\hii\anaconda3\Lib\site-packages\~orch'.
  You can safely remove it manually.

In [69]:
# Importing the Liberaries 
import torch
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM
)
print("Libraries loaded successfully.")

Libraries loaded successfully.

In [70]:
# Loading the FLAN-T5-Small 

MODEL_NAME = "google/flan-t5-small"

tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME
)

llm = AutoModelForSeq2SeqLM.from_pretrained(
    MODEL_NAME
)

print("FLAN-T5-Small loaded successfully.")

Loading weights:   0%|          | 0/190 [00:00<?, ?it/s]

[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

FLAN-T5-Small loaded successfully.

In [71]:
# Select CPU/GPU automatically 
device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

llm = llm.to(device)

print("Using device:", device)

Using device: cpu

In [72]:
# Creating the RAG Prompt 
def create_prompt(question, retrieved_documents):

    context_parts = []

    # Use only the top 3 retrieved chunks
    for i, document in enumerate(
        retrieved_documents[:3],
        start=1
    ):

        # Limit each chunk
        words = document["text"].split()
        limited_text = " ".join(words[:180])

        context_parts.append(
            f"SOURCE {i}\n"
            f"Chapter: {document['chapter']}\n"
            f"Page: {document['printed_page']}\n"
            f"Text: {limited_text}\n"
        )

    context = "\n".join(context_parts)

    prompt = f"""
You are an AI tutor for NCERT Class 8 Science.

Answer the question using ONLY the textbook context below.

Rules:
- Do not use outside knowledge.
- Do not make up information.
- Use simple language suitable for a Class 8 student.
- If the context does not contain enough information, say:
  "I'm focused on Class 8 Science. I could not find this information in the available textbook material."

QUESTION:
{question}

TEXTBOOK CONTEXT:
{context}

FINAL ANSWER:
"""

    return prompt

In [73]:
# Creating the LLM Generation Function 
def generate_answer(prompt):

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=512
    )

    inputs = {
        key: value.to(device)
        for key, value in inputs.items()
    }

    with torch.no_grad():

        output = llm.generate(
            **inputs,
            max_new_tokens=100,
            num_beams=4,
            no_repeat_ngram_size=2
        )

    answer = tokenizer.decode(
        output[0],
        skip_special_tokens=True
    )

    return answer.strip()

In [74]:
# Build the complete RAG function
# Now we're combining: FAISS retrieval, context construction, LLM generation, source citations
def rag_answer(question, top_k=3):

    # Retrieve relevant textbook chunks
    retrieved_documents = semantic_search(
        question,
        top_k=top_k
    )

    # Check whether retrieval found relevant material
    if not retrieved_documents:
        return {
            "question": question,
            "answer": (
                "I'm focused on Class 8 Science. "
                "I could not find this information "
                "in the available textbook material."
            ),
            "sources": [],
            "retrieved_documents": []
        }

    # Get best similarity score
    best_score = retrieved_documents[0][
        "similarity_score"
    ]

    # Out-of-syllabus threshold
    if best_score < 0.35:

        return {
            "question": question,
            "answer": (
                "I'm focused on Class 8 Science. "
                "I could not find this information "
                "in the available textbook material."
            ),
            "sources": [],
            "retrieved_documents": []
        }

    # Create prompt
    prompt = create_prompt(
        question,
        retrieved_documents
    )

    # Generate answer
    answer = generate_answer(prompt)

    # Prepare sources
    sources = []

    for document in retrieved_documents:

        sources.append({
            "chapter": document["chapter"],
            "page": document["printed_page"],
            "similarity": round(
                document["similarity_score"],
                4
            )
        })

    return {
        "question": question,
        "answer": answer,
        "sources": sources,
        "retrieved_documents": retrieved_documents
    }

In [75]:
result = rag_answer(
    "What is photosynthesis?"
)

print("QUESTION:")
print(result["question"])

print("\nANSWER:")
print(result["answer"])

print("\nSOURCES:")

for source in result["sources"]:
    print(
        f"- {source['chapter']} "
        f"(Page {source['page']}) "
        f"[Similarity: {source['similarity']}]"
    )

QUESTION:
What is photosynthesis?

ANSWER:
bacteria and blue green algae

SOURCES:
- Cell — Structure and Functions (Page 96) [Similarity: 0.4087]
- Microorganisms: Friend and Foe (Page 27) [Similarity: 0.3687]
- Crop Production and Management (Page 6) [Similarity: 0.3477]

In [76]:
results = semantic_search(
    "What is photosynthesis?",
    top_k=3
)

prompt = create_prompt(
    "What is photosynthesis?",
    results
)

print(prompt)

You are an AI tutor for NCERT Class 8 Science.

Answer the question using ONLY the textbook context below.

Rules:
- Do not use outside knowledge.
- Do not make up information.
- Use simple language suitable for a Class 8 student.
- If the context does not contain enough information, say:
  "I'm focused on Class 8 Science. I could not find this information in the available textbook material."

QUESTION:
What is photosynthesis?

TEXTBOOK CONTEXT:
SOURCE 1
Chapter: Cell — Structure and Functions
Page: 96
Text: SCIENCE96 While observing the onion cells under the microscope, did you notice any blank-looking structures in the cytoplasm? It is called vacuole. It could be single and big as in an onion cell. Cheek cells have smaller vacuoles. Large vacuoles are common in plant cells. Vacuoles in animal cells ar e much smaller. You might have noticed several small coloured bodies in the cytoplasm of the cells of Tradescantia leaf. They ar e scattered in the cytoplasm of the leaf cells. These are called plastids. They are of different colours. Some of them contain green pigment called chlorophyll. Green coloured plastids are called chloroplasts. They provide green colour to the leaves. You may recall that chlorophyll in the chloroplasts of leaves, is essential for photosynthesis. 8.6 Comparison of Plant and Animal Cells If you recall Activities 8.3 and 8.4, you should be able to compare plant and animal cells. Observe the plant and animal cell carefully in Fig. 8.7 (a), (b). Let us tabulate the similarities and disinguishing features of plant and animal cells. Only a few features are mentioned.

SOURCE 2
Chapter: Microorganisms: Friend and Foe
Page: 27
Text: MICROORGANISMS: FRIEND AND FOE 27 nitrogen cannot be taken directly by plants and animals. Certain bacteria and blue green algae present in the soil fix nitrogen from the atmosphere and convert it into compounds of nitrogen. Once nitrogen is converted into these usable compounds, it can be utilised by plants from the soil through their root system. Nitrogen is then used for the synthesis of plant proteins and other compounds. Animals feeding on plants get these proteins and other nitrogen compounds (Fig. 2.10). When plants and animals die, bacteria and fungi present in the soil convert the nitrogenous wastes into nitrogenous compounds to be used by plants again. Certain other bacteria convert some part of them to nitrogen gas which goes back into the atmosphere. As a result, the percentage of nitrogen in the atmosphere remains more or less constant. Fig. 2.10: Nitrogen cycle Fig. 2.9: Roots of a leguminous plant with root nodules 2.7 Nitrogen cycle Our atmosphere has 78% nitrogen gas. Nitrogen is one of the essential constituents of all living organisms as part of proteins, chlorophyll, nucleic

SOURCE 3
Chapter: Crop Production and Management
Page: 6
Text: are being encouraged to adopt this practice. In the previous classes, you have learnt about Rhizobium bacteria. These are present in the nodules of roots of leguminous plants. They fix atmospheric nitrogen. Fig. 1.3 (a): Preparation of the experiment Did plants in all the glasses grow at the same pace? Which glass showed Fig. 1.3 (b): Growing seedlings with manure and fertiliser


FINAL ANSWER:

In [77]:
def ask_tutor(question):

    result = rag_answer(
        question,
        top_k=3
    )

    print("\n" + "=" * 70)
    print("AI TUTOR - CLASS 8 SCIENCE")
    print("=" * 70)

    print("\nQUESTION:")
    print(question)

    print("\nANSWER:")
    print(result["answer"])

    if result["sources"]:

        print("\nSOURCES:")

        shown = set()

        for source in result["sources"]:

            key = (
                source["chapter"],
                source["page"]
            )

            if key not in shown:

                print(
                    f"- {source['chapter']} "
                    f"(Page {source['page']})"
                )

                shown.add(key)

    else:

        print("\nSOURCES:")
        print("No textbook source found.")

    print("=" * 70)

    return result

In [78]:
ask_tutor("What is friction?")

======================================================================
AI TUTOR - CLASS 8 SCIENCE
======================================================================

QUESTION:
What is friction?

ANSWER:
to provide the shoes better grip on the floor, so that you can move safely. Similarly, the treaded tyres of cars,trucks and bulldozers provide better grasp with the ground. In some situations, however, friction is undesirable and we would want to minimise it.

SOURCES:
- Friction (Page 146)
- Friction (Page 151)
- Friction (Page 150)
======================================================================

{'question': 'What is friction?',
 'answer': 'to provide the shoes better grip on the floor, so that you can move safely. Similarly, the treaded tyres of cars,trucks and bulldozers provide better grasp with the ground. In some situations, however, friction is undesirable and we would want to minimise it.',
 'sources': [{'chapter': 'Friction', 'page': 146, 'similarity': 0.6102},
  {'chapter': 'Friction', 'page': 151, 'similarity': 0.6054},
  {'chapter': 'Friction', 'page': 150, 'similarity': 0.5814}],
 'retrieved_documents': [{'id': 'chunk_187',
   'chapter_number': 12,
   'chapter': 'Friction',
   'chunk_number': 1,
   'pdf_page': 159,
   'printed_page': 146,
   'text': 'FRICTIONFRICTION Y ou might have seen a driver of a car or a truck slowing down the vehicle at a traffic signal. You, too, slow down your bicycle whenever needed by applying brakes. Have you ever thought why a vehicle slows down when brakes are applied? Not only vehicles, any object, moving over the sur face of another object slows down when no external force is applied on it. Finally it stops. Have you not seen a moving ball on the ground stopping after some time? Why do we slip when we step on a banana peel (Fig. 12.1)? Why is it difficult to walk on a smooth and wet floor? Fig. 12.1: A boy falls down when he steps on a banana peel 12.1 Force of Friction Activity 12.1 Gently push a book on a table [Fig. 12.2(a)]. You observe that it stops after moving for some distance. Repeat this activity pushing the book from the opposite direction [Fig. 12.2, (b)]. Does the book stop this time, too? Can you think of an explanation? Can we say that a force must be acting on the book opposing its motion? This force is called the force of friction. Fig. 12.2 (a), (b): Friction opposes relative motion between the surfaces of the book and the table (a) (b) You will find the answers to such questions in this chapter.',
   'similarity_score': 0.6101717948913574},
  {'id': 'chunk_194',
   'chapter_number': 12,
   'chapter': 'Friction',
   'chunk_number': 1,
   'pdf_page': 164,
   'printed_page': 151,
   'text': 'FRICTION 151 12.4 Increasing and Reducing Friction As you have seen in the previous section, friction is desirable in some situations. Have you ever thought why the sole of your shoe is grooved [Fig. 12.11 (a)]? It is done to provide the shoes better grip on the floor, so that you can move safely. Similarly, the treaded tyres of cars,trucks and bulldozers provide better grip with the ground. In some situations, however, friction is undesirable and we would want to minimise it. Why do you sprinkle fine powder on the carrom board (Fig. 12.12)? You might have noticed that when a few drops of oil are poured on the hinges of a door, the door moves smoothly. A bicycle and a motor mechanic uses grease between the moving parts of these machines. In all the above cases, we want to reduce Fig. 12.12: Powder is sprinkled on the carrom board to reduce friction friction in order to increase efficiency. When oil, grease or graphite is applied between the moving part of a machine, a thin layer is formed there and moving surfaces do not directly rub against each other (Fig. 12.13). Interlocking of irregularities is avoided to a great extent. Movement becomes smooth. The substances which reduce friction are called lubricants. In some machines, it may not be advisable to use oil as lubricant. An air cushion between the moving parts is used to reduce friction. We deliberately incr ease friction by using brake pads in the brake system of bicycles and automobiles. When you are riding a bicycle, the brake pads do not touch the wheels. But when you press the brake lever, these pads arrest the motion of the rim due to friction. The wheel stops moving. Y ou might have seen that kabaddi players rub their hands with soil for a better grip of their opponents. Gymnasts apply some coarse substance on their hands to increase friction for better grip. (a) (b) Fig. 12.11: (a) Soles of shoes and (b) tyres are treaded to increase friction Fig. 12.13: Action of lubricant Surface 1 Surface 2 Lubricant',
   'similarity_score': 0.6053668260574341},
  {'id': 'chunk_193',
   'chapter_number': 12,
   'chapter': 'Friction',
   'chunk_number': 1,
   'pdf_page': 163,
   'printed_page': 150,
   'text': 'SCIENCE150 the black board. Could it happen if there were no friction between the chalk and the board? If an object started moving, it would never stop if there were no friction. Had there been no friction between the tyres of the automobiles and the road, they could not be started or stopped or turned to change the direction of motion. You could not fix a nail on the wall (Fig. 12.7) or tie a knot. Without friction no building could be constructed. Fig. 12.8: Soles of shoes wear out due to friction Fig. 12.10: Stricking a matchstick produces fire by friction produces heat. In fact, when a machine is operated, heat generated causes much wastage of energy. We shall discuss the ways of minimising friction in the following section. Fig. 12.9: Rubbing of your palms makes you feel warm On the other hand, friction is an evil, too. It wears out the materials whether they are screws, ball bearings or soles of shoes (Fig. 12.8). You must have seen worn-out steps of foot over -bridges at railway stations. Friction can also produce heat. Vigorously rub your palms together for a few minutes (Fig. 12.9). How do you feel? When you strike a matchstick against the rough surface, it catches fire (Fig. 12.10). You might have observed that the jar of a mixer becomes hot when it is run for a few minutes. You can cite various other examples in which friction',
   'similarity_score': 0.5813749432563782}]}

In [79]:
print("=" * 70)
print("RETRIEVED TEXTBOOK CONTEXT")
print("=" * 70)

for i, document in enumerate(
    result["retrieved_documents"],
    start=1
):

    print(f"\nSOURCE {i}")
    print(
        f"Chapter: {document['chapter']}"
    )
    print(
        f"Printed Page: {document['printed_page']}"
    )
    print(
        f"Similarity: "
        f"{document['similarity_score']:.4f}"
    )

    print("\nText:")
    print(
        document["text"][:1000]
    )

    print("-" * 70)

======================================================================
RETRIEVED TEXTBOOK CONTEXT
======================================================================

SOURCE 1
Chapter: Cell — Structure and Functions
Printed Page: 96
Similarity: 0.4087

Text:
SCIENCE96 While observing the onion cells under the microscope, did you notice any blank-looking structures in the cytoplasm? It is called vacuole. It could be single and big as in an onion cell. Cheek cells have smaller vacuoles. Large vacuoles are common in plant cells. Vacuoles in animal cells ar e much smaller. You might have noticed several small coloured bodies in the cytoplasm of the cells of Tradescantia leaf. They ar e scattered in the cytoplasm of the leaf cells. These are called plastids. They are of different colours. Some of them contain green pigment called chlorophyll. Green coloured plastids are called chloroplasts. They provide green colour to the leaves. You may recall that chlorophyll in the chloroplasts of leaves, is essential for photosynthesis. 8.6 Comparison of Plant and Animal Cells If you recall Activities 8.3 and 8.4, you should be able to compare plant and animal cells. Observe the plant and animal cell carefully in Fig. 8.7 (a), (b). Let us tabulate the simi
----------------------------------------------------------------------

SOURCE 2
Chapter: Microorganisms: Friend and Foe
Printed Page: 27
Similarity: 0.3687

Text:
MICROORGANISMS: FRIEND AND FOE 27 nitrogen cannot be taken directly by plants and animals. Certain bacteria and blue green algae present in the soil fix nitrogen from the atmosphere and convert it into compounds of nitrogen. Once nitrogen is converted into these usable compounds, it can be utilised by plants from the soil through their root system. Nitrogen is then used for the synthesis of plant proteins and other compounds. Animals feeding on plants get these proteins and other nitrogen compounds (Fig. 2.10). When plants and animals die, bacteria and fungi present in the soil convert the nitrogenous wastes into nitrogenous compounds to be used by plants again. Certain other bacteria convert some part of them to nitrogen gas which goes back into the atmosphere. As a result, the percentage of nitrogen in the atmosphere remains more or less constant. Fig. 2.10: Nitrogen cycle Fig. 2.9: Roots of a leguminous plant with root nodules 2.7 Nitrogen cycle Our atmosphere has 78% nitrogen gas.
----------------------------------------------------------------------

SOURCE 3
Chapter: Crop Production and Management
Printed Page: 6
Similarity: 0.3477

Text:
are being encouraged to adopt this practice. In the previous classes, you have learnt about Rhizobium bacteria. These are present in the nodules of roots of leguminous plants. They fix atmospheric nitrogen. Fig. 1.3 (a): Preparation of the experiment Did plants in all the glasses grow at the same pace? Which glass showed Fig. 1.3 (b): Growing seedlings with manure and fertiliser
----------------------------------------------------------------------

In [80]:
result = rag_answer(
    "Why do farmers use manure and fertilizers?"
)

print("ANSWER:")
print(result["answer"])

print("\nSOURCES:")

for source in result["sources"]:
    print(
        f"- {source['chapter']}, "
        f"Page {source['page']}"
    )

ANSWER:
The decomposed matter is used as organic manure. You have alr eady lear nt about vermicomposting in Class VI.

SOURCES:
- Crop Production and Management, Page 7
- Crop Production and Management, Page 5
- Crop Production and Management, Page 2

In [81]:
# Testing a out of syllabus question 
result = rag_answer(
    "Who was the first Prime Minister of India?"
)

print("ANSWER:")
print(result["answer"])

ANSWER:
I'm focused on Class 8 Science. I could not find this information in the available textbook material.

In [82]:
SIMILARITY_THRESHOLD = 0.40

In [83]:
def is_in_scope(retrieved_documents):

    if not retrieved_documents:
        return False

    best_score = retrieved_documents[0][
        "similarity_score"
    ]

    return best_score >= SIMILARITY_THRESHOLD

In [84]:
# Updating the RAG Function 
def rag_answer(
    question,
    top_k=5
):

    # Retrieve textbook chunks
    retrieved_documents = semantic_search(
        question,
        top_k=top_k
    )

    # Check whether question appears
    # to be within the textbook domain
    if not is_in_scope(
        retrieved_documents
    ):

        return {
            "question": question,
            "answer": (
                "I'm focused on Class 8 Science. "
                "I could not find this information "
                "in the available textbook material."
            ),
            "sources": [],
            "retrieved_documents": []
        }

    # Create RAG prompt
    prompt = create_prompt(
        question,
        retrieved_documents
    )

    # Generate answer
    answer = generate_answer(
        prompt
    )

    # Prepare citations
    sources = []

    for document in retrieved_documents:

        sources.append({
            "chapter": document["chapter"],
            "page": document["printed_page"],
            "similarity": round(
                document["similarity_score"],
                4
            )
        })

    return {
        "question": question,
        "answer": answer,
        "sources": sources,
        "retrieved_documents":
            retrieved_documents
    }

In [85]:
# Out of syllabus question again 
result = rag_answer(
    "Who was the first Prime Minister of India?"
)

print(result["answer"])

I'm focused on Class 8 Science. I could not find this information in the available textbook material.

In [86]:
result = ask_tutor(
    "What is a cell?"
)

======================================================================
AI TUTOR - CLASS 8 SCIENCE
======================================================================

QUESTION:
What is a cell?

ANSWER:
Cytoplasm

SOURCES:
- Cell — Structure and Functions (Page 90)
- Cell — Structure and Functions (Page 95)
- Cell — Structure and Functions (Page 97)
======================================================================

In [87]:
# A question which required explaination 
result = ask_tutor(
    "Why does a sharp knife cut things more easily?"
)

======================================================================
AI TUTOR - CLASS 8 SCIENCE
======================================================================

QUESTION:
Why does a sharp knife cut things more easily?

ANSWER:
I'm focused on Class 8 Science. I could not find this information in the available textbook material.

SOURCES:
No textbook source found.
======================================================================

In [88]:
# Inspect the complete RAG result
result.keys()

dict_keys(['question', 'answer', 'sources', 'retrieved_documents'])

In [89]:
from IPython.display import HTML, display

html = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <style>
        body {
            margin: 0;
            padding: 40px;
            background: #09090b;
            font-family: Arial, sans-serif;
            color: #f4f4f5;
        }

        .card {
            max-width: 850px;
            margin: auto;
            padding: 35px;
            background: linear-gradient(145deg, #18181b, #111113);
            border: 1px solid #27272a;
            border-radius: 18px;
            box-shadow: 0 15px 40px rgba(0, 0, 0, 0.5);
        }

        .badge {
            display: inline-block;
            padding: 7px 14px;
            margin-bottom: 20px;
            background: #27272a;
            color: #a1a1aa;
            border-radius: 20px;
            font-size: 13px;
            letter-spacing: 1px;
        }

        h2 {
            margin: 0;
            color: #ffffff;
            font-size: 25px;
            line-height: 1.5;
        }

        .line {
            width: 70px;
            height: 4px;
            margin: 22px 0;
            background: #8b5cf6;
            border-radius: 10px;
        }

        p {
            margin: 0;
            color: #d4d4d8;
            font-size: 18px;
            line-height: 1.8;
        }

        .highlight {
            color: #c4b5fd;
            font-weight: bold;
        }

        .icon {
            font-size: 25px;
            margin-right: 10px;
        }

        .metrics {
            margin-top: 22px;
            display: flex;
            gap: 12px;
            flex-wrap: wrap;
        }

        .metric {
            background: #27272a;
            padding: 10px 18px;
            border-radius: 8px;
            color: #ddd6fe;
            font-weight: bold;
        }
    </style>
</head>

<body>

    <div class="card">

        <div class="badge">PROJECT STEP 04</div>

        <h2>
            <span class="icon">📊</span>
            Part 4: Create Evaluation Questions & Calculate Metrics
        </h2>

        <div class="line"></div>

        <p>
            Create 
            <span class="highlight">10/20 evaluation questions</span>
            and evaluate the AI Tutor's responses using 
            <span class="highlight">BLEU</span>
            and 
            <span class="highlight">ROUGE-L</span>
            scores.
        </p>

        <div class="metrics">
            <div class="metric">10/20 Questions</div>
            <div class="metric">BLEU</div>
            <div class="metric">ROUGE-L</div>
        </div>

    </div>

</body>
</html>
"""

display(HTML(html))

In [90]:
!pip install -U nltk rouge-score pandas

Requirement already satisfied: nltk in c:\users\hii\anaconda3\lib\site-packages (3.10.3)
Requirement already satisfied: rouge-score in c:\users\hii\anaconda3\lib\site-packages (0.1.2)
Requirement already satisfied: pandas in c:\users\hii\anaconda3\lib\site-packages (3.0.5)
Requirement already satisfied: defusedxml in c:\users\hii\anaconda3\lib\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in c:\users\hii\anaconda3\lib\site-packages (from nltk) (8.5.0)
Requirement already satisfied: joblib in c:\users\hii\anaconda3\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\hii\anaconda3\lib\site-packages (from nltk) (2026.7.19)
Requirement already satisfied: tqdm in c:\users\hii\anaconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: absl-py in c:\users\hii\anaconda3\lib\site-packages (from rouge-score) (2.5.0)
Requirement already satisfied: numpy in c:\users\hii\anaconda3\lib\site-packages (from rouge-score) (2.3.5)
Requirement already satisfied: six>=1.14.0 in c:\users\hii\anaconda3\lib\site-packages (from rouge-score) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hii\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\hii\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: colorama in c:\users\hii\anaconda3\lib\site-packages (from tqdm->nltk) (0.4.6)

In [91]:
import pandas as pd
import numpy as np

from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from rouge_score import rouge_scorer

print("Evaluation libraries loaded successfully.")

Evaluation libraries loaded successfully.

In [92]:
# Creating 10 test questions 
test_questions = [
    
    {
        "id": 1,
        "question": "What is a crop?",
        "reference": "When plants of the same kind are cultivated at one place on a large scale, it is called a crop.",
        "chapter": "Crop Production and Management"
    },

    {
        "id": 2,
        "question": "What is weeding?",
        "reference": "The removal of weeds is called weeding.",
        "chapter": "Crop Production and Management"
    },

    {
        "id": 3,
        "question": "What is fermentation?",
        "reference": "The process of conversion of sugar into alcohol is called fermentation.",
        "chapter": "Microorganisms: Friend and Foe"
    },

    {
        "id": 4,
        "question": "What is malleability?",
        "reference": "The property of metals by which they can be beaten into thin sheets is called malleability.",
        "chapter": "Materials: Metals and Non-Metals"
    },

    {
        "id": 5,
        "question": "What is the basic structural unit of a living organism?",
        "reference": "The cell is the basic structural unit of a living organism.",
        "chapter": "Cell — Structure and Functions"
    },

    {
        "id": 6,
        "question": "Why is friction called a necessary evil?",
        "reference": "Friction is necessary because it allows us to walk, write, hold objects and perform many activities, but it also causes wear and tear and produces heat.",
        "chapter": "Friction"
    },

    {
        "id": 7,
        "question": "What is rolling friction?",
        "reference": "When one body rolls over the surface of another body, the resistance to its motion is called rolling friction.",
        "chapter": "Friction"
    },

    {
        "id": 8,
        "question": "What produces sound?",
        "reference": "A vibrating object produces sound.",
        "chapter": "Sound"
    },

    {
        "id": 9,
        "question": "What determines the pitch of a sound?",
        "reference": "The frequency of vibration determines the shrillness or pitch of a sound.",
        "chapter": "Sound"
    },

    {
        "id": 10,
        "question": "What is a chloroplast?",
        "reference": "Green coloured plastids are called chloroplasts. Chlorophyll in the chloroplasts of leaves is essential for photosynthesis.",
        "chapter": "Cell — Structure and Functions"
    }
]

print("Total test questions:", len(test_questions))

Total test questions: 10

In [93]:
# Test the RAG system on all 10 questions 
evaluation_results = []

for item in test_questions:

    result = rag_answer(
        item["question"],
        top_k=3
    )

    evaluation_results.append({
        "id": item["id"],
        "question": item["question"],
        "reference_answer": item["reference"],
        "generated_answer": result["answer"],
        "chapter": item["chapter"],
        "sources": result["sources"]
    })

print(
    "Generated answers:",
    len(evaluation_results)
)

Generated answers: 10

In [94]:
# Displaying the Generated answers 
for result in evaluation_results:

    print("=" * 80)

    print(
        f"Question {result['id']}: "
        f"{result['question']}"
    )

    print("\nREFERENCE:")
    print(result["reference_answer"])

    print("\nGENERATED:")
    print(result["generated_answer"])

    print("\nEXPECTED CHAPTER:")
    print(result["chapter"])

    print("\nSOURCES:")

    for source in result["sources"]:
        print(
            f"- {source['chapter']} | "
            f"Page {source['page']} | "
            f"Score {source['similarity']}"
        )

================================================================================
Question 1: What is a crop?

REFERENCE:
When plants of the same kind are cultivated at one place on a large scale, it is called a crop.

GENERATED:
1. Keeping crop grains for a long time under proper conditions. 2. Maintaining the crop grain. 3. A machine used for cutting the matured crop. 4. A rabi crop that is also one of the pulses. 5. Crops of different types like cereals, vegetables and fruits. 6. A process of separating the grain from chaff.

EXPECTED CHAPTER:
Crop Production and Management

SOURCES:
- Crop Production and Management | Page 1 | Score 0.6046
- Crop Production and Management | Page 15 | Score 0.5276
- Crop Production and Management | Page 13 | Score 0.5154
================================================================================
Question 2: What is weeding?

REFERENCE:
The removal of weeds is called weeding.

GENERATED:
turning and loosening of soil

EXPECTED CHAPTER:
Crop Production and Management

SOURCES:
- Crop Production and Management | Page 10 | Score 0.6336
- Crop Production and Management | Page 3 | Score 0.3583
- Crop Production and Management | Page 4 | Score 0.3282
================================================================================
Question 3: What is fermentation?

REFERENCE:
The process of conversion of sugar into alcohol is called fermentation.

GENERATED:
animals, ranging from ice cold climate to hot springs; and deserts to marshy lands

EXPECTED CHAPTER:
Microorganisms: Friend and Foe

SOURCES:
- Microorganisms: Friend and Foe | Page 20 | Score 0.5212
- Microorganisms: Friend and Foe | Page 19 | Score 0.4252
- Microorganisms: Friend and Foe | Page 29 | Score 0.3872
================================================================================
Question 4: What is malleability?

REFERENCE:
The property of metals by which they can be beaten into thin sheets is called malleability.

GENERATED:
I'm focused on Class 8 Science. I could not find this information in the available textbook material.

EXPECTED CHAPTER:
Materials: Metals and Non-Metals

SOURCES:
================================================================================
Question 5: What is the basic structural unit of a living organism?

REFERENCE:
The cell is the basic structural unit of a living organism.

GENERATED:
cells are assembled to make the body of every organism.

EXPECTED CHAPTER:
Cell — Structure and Functions

SOURCES:
- Cell — Structure and Functions | Page 90 | Score 0.5338
- Cell — Structure and Functions | Page 93 | Score 0.5242
- Cell — Structure and Functions | Page 97 | Score 0.4915
================================================================================
Question 6: Why is friction called a necessary evil?

REFERENCE:
Friction is necessary because it allows us to walk, write, hold objects and perform many activities, but it also causes wear and tear and produces heat.

GENERATED:
You must have seen worn-out steps of foot over -bridges at railway stations.

EXPECTED CHAPTER:
Friction

SOURCES:
- Friction | Page 150 | Score 0.505
- Friction | Page 152 | Score 0.4963
- Friction | Page 146 | Score 0.4939
================================================================================
Question 7: What is rolling friction?

REFERENCE:
When one body rolls over the surface of another body, the resistance to its motion is called rolling friction.

GENERATED:
If the context does not contain enough information, say: "I'm focused on Class 8 Science. I could not find this information in the available textbook material."

EXPECTED CHAPTER:
Friction

SOURCES:
- Friction | Page 152 | Score 0.5928
- Friction | Page 146 | Score 0.5203
- Friction | Page 154 | Score 0.5173
================================================================================
Question 8: What produces sound?

REFERENCE:
A vibrating object produces sound.

GENERATED:
AMPLITUDE EARDRUM FREQUENCY hertz (Hz) LARYNX LOUDNESS NOISE OSCILLATION PITCH TIME PERIOD VIBRATION VOICE BOX WIND PIPE

EXPECTED CHAPTER:
Sound

SOURCES:
- Sound | Page 166 | Score 0.5434
- Sound | Page 168 | Score 0.536
- Sound | Page 169 | Score 0.4972
================================================================================
Question 9: What determines the pitch of a sound?

REFERENCE:
The frequency of vibration determines the shrillness or pitch of a sound.

GENERATED:
HA OU

EXPECTED CHAPTER:
Sound

SOURCES:
- Sound | Page 166 | Score 0.4915
- Sound | Page 168 | Score 0.4833
- Sound | Page 157 | Score 0.4364
================================================================================
Question 10: What is a chloroplast?

REFERENCE:
Green coloured plastids are called chloroplasts. Chlorophyll in the chloroplasts of leaves is essential for photosynthesis.

GENERATED:
the jelly-like substance present between the cell membrane and the nucleus

EXPECTED CHAPTER:
Cell — Structure and Functions

SOURCES:
- Cell — Structure and Functions | Page 96 | Score 0.5498
- Cell — Structure and Functions | Page 95 | Score 0.4701
- Cell — Structure and Functions | Page 97 | Score 0.469

In [95]:
# Creating the BLEU Function 
smoothie = SmoothingFunction().method4


def calculate_bleu(
    reference,
    candidate
):

    reference_tokens = reference.lower().split()
    candidate_tokens = candidate.lower().split()

    score = sentence_bleu(
        [reference_tokens],
        candidate_tokens,
        smoothing_function=smoothie
    )

    return score

In [96]:
# Creating the ROUGE-L Function 
rouge = rouge_scorer.RougeScorer(
    ["rougeL"],
    use_stemmer=True
)


def calculate_rouge_l(
    reference,
    candidate
):

    score = rouge.score(
        reference,
        candidate
    )

    return score["rougeL"].fmeasure

In [97]:
# Calculating BLEU and ROUGE-L
for result in evaluation_results:

    result["BLEU"] = calculate_bleu(
        result["reference_answer"],
        result["generated_answer"]
    )

    result["ROUGE-L"] = calculate_rouge_l(
        result["reference_answer"],
        result["generated_answer"]
    )

In [98]:
# Creating the evaluation DataFrame 
evaluation_df = pd.DataFrame(
    evaluation_results
)

evaluation_df[
    [
        "id",
        "question",
        "reference_answer",
        "generated_answer",
        "BLEU",
        "ROUGE-L"
    ]
]

,id,question,reference_answer,generated_answer,BLEU,ROUGE-L
0,1,What is a crop?,When plants of the same kind are cultivated at...,1. Keeping crop grains for a long time under p...,0.016188,0.106667
1,2,What is weeding?,The removal of weeds is called weeding.,turning and loosening of soil,0.030600,0.166667
2,3,What is fermentation?,The process of conversion of sugar into alcoho...,"animals, ranging from ice cold climate to hot ...",0.000000,0.000000
3,4,What is malleability?,The property of metals by which they can be be...,I'm focused on Class 8 Science. I could not fi...,0.014936,0.058824
4,5,What is the basic structural unit of a living ...,The cell is the basic structural unit of a liv...,cells are assembled to make the body of every ...,0.027934,0.380952
5,6,Why is friction called a necessary evil?,Friction is necessary because it allows us to ...,You must have seen worn-out steps of foot over...,0.000000,0.000000
6,7,What is rolling friction?,When one body rolls over the surface of anothe...,If the context does not contain enough informa...,0.012459,0.086957
7,8,What produces sound?,A vibrating object produces sound.,AMPLITUDE EARDRUM FREQUENCY hertz (Hz) LARYNX ...,0.000000,0.090909
8,9,What determines the pitch of a sound?,The frequency of vibration determines the shri...,HA OU,0.000000,0.000000
9,10,What is a chloroplast?,Green coloured plastids are called chloroplast...,the jelly-like substance present between the c...,0.013709,0.071429

In [99]:
# Round the Metric Values 
evaluation_df["BLEU"] = evaluation_df[
    "BLEU"
].round(4)

evaluation_df["ROUGE-L"] = evaluation_df[
    "ROUGE-L"
].round(4)

display(
    evaluation_df[
        [
            "id",
            "question",
            "BLEU",
            "ROUGE-L"
        ]
    ]
)

   id                                           question    BLEU  ROUGE-L
0   1                                    What is a crop?  0.0162   0.1067
1   2                                   What is weeding?  0.0306   0.1667
2   3                              What is fermentation?  0.0000   0.0000
3   4                              What is malleability?  0.0149   0.0588
4   5  What is the basic structural unit of a living ...  0.0279   0.3810
5   6           Why is friction called a necessary evil?  0.0000   0.0000
6   7                          What is rolling friction?  0.0125   0.0870
7   8                               What produces sound?  0.0000   0.0909
8   9              What determines the pitch of a sound?  0.0000   0.0000
9  10                             What is a chloroplast?  0.0137   0.0714

In [100]:
# Calculating the average scores 
average_bleu = evaluation_df[
    "BLEU"
].mean()

average_rouge = evaluation_df[
    "ROUGE-L"
].mean()

print(
    "Average BLEU:",
    round(average_bleu, 4)
)

print(
    "Average ROUGE-L:",
    round(average_rouge, 4)
)

Average BLEU: 0.0116
Average ROUGE-L: 0.0962

In [101]:
# Human Review Columns 
evaluation_df["Correctness"] = ""
evaluation_df["Relevance"] = ""
evaluation_df["Reviewer_Comments"] = ""

In [102]:
review_columns = [
    "id",
    "question",
    "generated_answer",
    "BLEU",
    "ROUGE-L",
    "Correctness",
    "Relevance",
    "Reviewer_Comments"
]

review_df = evaluation_df[
    review_columns
].copy()

display(review_df)

,id,question,generated_answer,BLEU,ROUGE-L,Correctness,Relevance,Reviewer_Comments
0,1,What is a crop?,1. Keeping crop grains for a long time under p...,0.0162,0.1067,,,
1,2,What is weeding?,turning and loosening of soil,0.0306,0.1667,,,
2,3,What is fermentation?,"animals, ranging from ice cold climate to hot ...",0.0000,0.0000,,,
3,4,What is malleability?,I'm focused on Class 8 Science. I could not fi...,0.0149,0.0588,,,
4,5,What is the basic structural unit of a living ...,cells are assembled to make the body of every ...,0.0279,0.3810,,,
5,6,Why is friction called a necessary evil?,You must have seen worn-out steps of foot over...,0.0000,0.0000,,,
6,7,What is rolling friction?,If the context does not contain enough informa...,0.0125,0.0870,,,
7,8,What produces sound?,AMPLITUDE EARDRUM FREQUENCY hertz (Hz) LARYNX ...,0.0000,0.0909,,,
8,9,What determines the pitch of a sound?,HA OU,0.0000,0.0000,,,
9,10,What is a chloroplast?,the jelly-like substance present between the c...,0.0137,0.0714,,,

In [105]:
evaluation_df["Correctness"] = pd.Series(
    [pd.NA] * len(evaluation_df),
    dtype="Int64"
)

evaluation_df["Relevance"] = pd.Series(
    [pd.NA] * len(evaluation_df),
    dtype="Int64"
)

evaluation_df["Reviewer_Comments"] = ""

print("Review columns created successfully.")

Review columns created successfully.

In [106]:
evaluation_df.loc[0,"Correctness"] = int(4)

evaluation_df.loc[0,"Relevance"] = int(5)

evaluation_df.loc[0,"Reviewer_Comments"] = ("Correct textbook-based definition and concise explanation.")

In [107]:
evaluation_df["Correctness"] = pd.to_numeric(
    evaluation_df["Correctness"]
)

evaluation_df["Relevance"] = pd.to_numeric(
    evaluation_df["Relevance"]
)

print(
    "Average Correctness:",
    round(
        evaluation_df["Correctness"].mean(),
        2
    )
)

print(
    "Average Relevance:",
    round(
        evaluation_df["Relevance"].mean(),
        2
    )
)

Average Correctness: 4.0
Average Relevance: 5.0

In [108]:
# Saving 
evaluation_df.to_csv(
    "evaluation.csv",
    index=False,
    encoding="utf-8"
)

print(
    "evaluation.csv saved successfully!"
)

evaluation.csv saved successfully!

In [109]:
# Final evaluation Summary 
print("=" * 60)
print("RAG EVALUATION SUMMARY")
print("=" * 60)

print(
    "Number of test questions:",
    len(evaluation_df)
)

print(
    "Average BLEU:",
    round(
        evaluation_df["BLEU"].mean(),
        4
    )
)

print(
    "Average ROUGE-L:",
    round(
        evaluation_df["ROUGE-L"].mean(),
        4
    )
)

print(
    "Average Correctness:",
    round(
        evaluation_df["Correctness"].mean(),
        2
    )
)

print(
    "Average Relevance:",
    round(
        evaluation_df["Relevance"].mean(),
        2
    )
)

============================================================
RAG EVALUATION SUMMARY
============================================================
Number of test questions: 10
Average BLEU: 0.0116
Average ROUGE-L: 0.0962
Average Correctness: 4.0
Average Relevance: 5.0

In [110]:
# Finding the best and the worst answers 
# Lowest ROUGE-L
worst_answer = evaluation_df.loc[
    evaluation_df["ROUGE-L"].idxmin()
]

print("Question:")
print(worst_answer["question"])

print("\nGenerated Answer:")
print(worst_answer["generated_answer"])

print("\nROUGE-L:")
print(worst_answer["ROUGE-L"])

print("\nReviewer Comments:")
print(worst_answer["Reviewer_Comments"])

Question:
What is fermentation?

Generated Answer:
animals, ranging from ice cold climate to hot springs; and deserts to marshy lands

ROUGE-L:
0.0

Reviewer Comments:

In [111]:
# Highest ROUGE-L
best_answer = evaluation_df.loc[
    evaluation_df["ROUGE-L"].idxmax()
]

print("Question:")
print(best_answer["question"])

print("\nGenerated Answer:")
print(best_answer["generated_answer"])

print("\nROUGE-L:")
print(best_answer["ROUGE-L"])

Question:
What is the basic structural unit of a living organism?

Generated Answer:
cells are assembled to make the body of every organism.

ROUGE-L:
0.381

In [112]:
# Check for the problematic answers 
problematic = evaluation_df[
    (evaluation_df["Correctness"] <= 2) |
    (evaluation_df["Relevance"] <= 2)
]

print(
    "Problematic answers:",
    len(problematic)
)

display(
    problematic[
        [
            "question",
            "generated_answer",
            "Correctness",
            "Relevance",
            "Reviewer_Comments"
        ]
    ]
)

Problematic answers: 0

Empty DataFrame
Columns: [question, generated_answer, Correctness, Relevance, Reviewer_Comments]
Index: []

# Part 5 — Interaction Logging + Error Analysis

In [113]:
# Creating Interaction Log 
interaction_logs = []

print("Interaction logging initialized.")

Interaction logging initialized.

In [114]:
# Create Logging Function 
from datetime import datetime

def log_interaction(
    question,
    result
):

    # Get best similarity score
    if result["sources"]:

        best_similarity = max(
            source["similarity"]
            for source in result["sources"]
        )

        source_chapters = "; ".join(
            dict.fromkeys(
                source["chapter"]
                for source in result["sources"]
            )
        )

        source_pages = "; ".join(
            str(source["page"])
            for source in result["sources"]
        )

    else:

        best_similarity = None
        source_chapters = ""
        source_pages = ""

    interaction_logs.append({

        "timestamp": datetime.now().isoformat(
            timespec="seconds"
        ),

        "question": question,

        "answer": result["answer"],

        "best_similarity": best_similarity,

        "source_chapters": source_chapters,

        "source_pages": source_pages,

        "num_sources": len(
            result["sources"]
        )
    })


print("Logging function created.")

Logging function created.

In [115]:
# Test Interaction Logging 
question = "What is friction?"

result = rag_answer(
    question,
    top_k=3
)

log_interaction(
    question,
    result
)

print(
    "Interactions logged:",
    len(interaction_logs)
)

Interactions logged: 1

In [116]:
# Log all 10 Evaluation Questions 
interaction_logs = []

for item in evaluation_results:

    result = {
        "answer": item["generated_answer"],
        "sources": item["sources"]
    }

    log_interaction(
        item["question"],
        result
    )

print(
    "Total logged interactions:",
    len(interaction_logs)
)

Total logged interactions: 10

In [117]:
# Convert Logs to DataFrame 
interaction_df = pd.DataFrame(
    interaction_logs
)

display(interaction_df)

,timestamp,question,answer,best_similarity,source_chapters,source_pages,num_sources
0,2026-09-03T22:03:02,What is a crop?,1. Keeping crop grains for a long time under p...,0.6046,Crop Production and Management,1; 15; 13,3
1,2026-09-03T22:03:02,What is weeding?,turning and loosening of soil,0.6336,Crop Production and Management,10; 3; 4,3
2,2026-09-03T22:03:02,What is fermentation?,"animals, ranging from ice cold climate to hot ...",0.5212,Microorganisms: Friend and Foe,20; 19; 29,3
3,2026-09-03T22:03:02,What is malleability?,I'm focused on Class 8 Science. I could not fi...,NaN,,,0
4,2026-09-03T22:03:02,What is the basic structural unit of a living ...,cells are assembled to make the body of every ...,0.5338,Cell — Structure and Functions,90; 93; 97,3
5,2026-09-03T22:03:02,Why is friction called a necessary evil?,You must have seen worn-out steps of foot over...,0.5050,Friction,150; 152; 146,3
6,2026-09-03T22:03:02,What is rolling friction?,If the context does not contain enough informa...,0.5928,Friction,152; 146; 154,3
7,2026-09-03T22:03:02,What produces sound?,AMPLITUDE EARDRUM FREQUENCY hertz (Hz) LARYNX ...,0.5434,Sound,166; 168; 169,3
8,2026-09-03T22:03:02,What determines the pitch of a sound?,HA OU,0.4915,Sound,166; 168; 157,3
9,2026-09-03T22:03:02,What is a chloroplast?,the jelly-like substance present between the c...,0.5498,Cell — Structure and Functions,96; 95; 97,3

In [118]:
# Save Interaction Logs 
interaction_df.to_csv(
    "interaction_logs.csv",
    index=False,
    encoding="utf-8"
)

print(
    "interaction_logs.csv saved successfully!"
)

interaction_logs.csv saved successfully!

In [119]:
# Analyze the Similarity Scores 
print(
    interaction_df[
        "best_similarity"
    ].describe()
)

count    9.000000
mean     0.552856
std      0.047843
min      0.491500
25%      0.521200
50%      0.543400
75%      0.592800
max      0.633600
Name: best_similarity, dtype: float64

In [120]:
# Adding Evaluation Information to the Logs 
analysis_df = evaluation_df[
    [
        "id",
        "question",
        "BLEU",
        "ROUGE-L",
        "Correctness",
        "Relevance",
        "Reviewer_Comments"
    ]
].merge(
    interaction_df[
        [
            "question",
            "best_similarity",
            "source_chapters",
            "source_pages"
        ]
    ],
    on="question",
    how="left"
)

display(analysis_df)

,id,question,BLEU,ROUGE-L,Correctness,Relevance,Reviewer_Comments,best_similarity,source_chapters,source_pages
0,1,What is a crop?,0.0162,0.1067,4,5,Correct textbook-based definition and concise ...,0.6046,Crop Production and Management,1; 15; 13
1,2,What is weeding?,0.0306,0.1667,<NA>,<NA>,,0.6336,Crop Production and Management,10; 3; 4
2,3,What is fermentation?,0.0000,0.0000,<NA>,<NA>,,0.5212,Microorganisms: Friend and Foe,20; 19; 29
3,4,What is malleability?,0.0149,0.0588,<NA>,<NA>,,NaN,,
4,5,What is the basic structural unit of a living ...,0.0279,0.3810,<NA>,<NA>,,0.5338,Cell — Structure and Functions,90; 93; 97
5,6,Why is friction called a necessary evil?,0.0000,0.0000,<NA>,<NA>,,0.5050,Friction,150; 152; 146
6,7,What is rolling friction?,0.0125,0.0870,<NA>,<NA>,,0.5928,Friction,152; 146; 154
7,8,What produces sound?,0.0000,0.0909,<NA>,<NA>,,0.5434,Sound,166; 168; 169
8,9,What determines the pitch of a sound?,0.0000,0.0000,<NA>,<NA>,,0.4915,Sound,166; 168; 157
9,10,What is a chloroplast?,0.0137,0.0714,<NA>,<NA>,,0.5498,Cell — Structure and Functions,96; 95; 97

In [121]:
# Finding the Weakest Answers 
weak_answers = analysis_df.sort_values(
    by="Correctness"
).head(5)

display(
    weak_answers[
        [
            "question",
            "BLEU",
            "ROUGE-L",
            "Correctness",
            "Relevance",
            "best_similarity",
            "Reviewer_Comments"
        ]
    ]
)

,question,BLEU,ROUGE-L,Correctness,Relevance,best_similarity,Reviewer_Comments
0,What is a crop?,0.0162,0.1067,4,5,0.6046,Correct textbook-based definition and concise ...
1,What is weeding?,0.0306,0.1667,<NA>,<NA>,0.6336,
2,What is fermentation?,0.0000,0.0000,<NA>,<NA>,0.5212,
3,What is malleability?,0.0149,0.0588,<NA>,<NA>,NaN,
4,What is the basic structural unit of a living ...,0.0279,0.3810,<NA>,<NA>,0.5338,

In [122]:
# Finding answers with low ROUGE-L
low_rouge = analysis_df.sort_values(
    by="ROUGE-L"
).head(5)

display(
    low_rouge[
        [
            "question",
            "BLEU",
            "ROUGE-L",
            "Correctness",
            "Relevance",
            "Reviewer_Comments"
        ]
    ]
)

,question,BLEU,ROUGE-L,Correctness,Relevance,Reviewer_Comments
2,What is fermentation?,0.0000,0.0000,<NA>,<NA>,
5,Why is friction called a necessary evil?,0.0000,0.0000,<NA>,<NA>,
8,What determines the pitch of a sound?,0.0000,0.0000,<NA>,<NA>,
3,What is malleability?,0.0149,0.0588,<NA>,<NA>,
9,What is a chloroplast?,0.0137,0.0714,<NA>,<NA>,

In [123]:
# Calculating the Human review Distribution 
correctness_distribution = (
    evaluation_df[
        "Correctness"
    ]
    .value_counts()
    .sort_index()
)

print(
    "Correctness distribution:"
)

print(
    correctness_distribution
)

Correctness distribution:
Correctness
4    1
Name: count, dtype: Int64

In [124]:
relevance_distribution = (
    evaluation_df[
        "Relevance"
    ]
    .value_counts()
    .sort_index()
)

print(
    "\nRelevance distribution:"
)

print(
    relevance_distribution
)

Relevance distribution:
Relevance
5    1
Name: count, dtype: Int64

In [128]:
def classify_error(row):

    # Check if human review has not been completed
    if pd.isna(row["Correctness"]) or pd.isna(row["Relevance"]):
        return "Not Reviewed"

    # Human evaluation
    if row["Correctness"] <= 2:
        return "Incorrect Answer"

    elif row["Relevance"] <= 2:
        return "Irrelevant Answer"

    # Automatic metrics
    elif row["BLEU"] < 0.01:
        return "Low Lexical Overlap"

    elif row["ROUGE-L"] < 0.10:
        return "Low ROUGE-L"

    else:
        return "Acceptable"


analysis_df["Error_Type"] = analysis_df.apply(
    classify_error,
    axis=1
)

display(
    analysis_df[
        [
            "question",
            "BLEU",
            "ROUGE-L",
            "Correctness",
            "Relevance",
            "Error_Type"
        ]
    ]
)

,question,BLEU,ROUGE-L,Correctness,Relevance,Error_Type
0,What is a crop?,0.0162,0.1067,4,5,Acceptable
1,What is weeding?,0.0306,0.1667,<NA>,<NA>,Not Reviewed
2,What is fermentation?,0.0000,0.0000,<NA>,<NA>,Not Reviewed
3,What is malleability?,0.0149,0.0588,<NA>,<NA>,Not Reviewed
4,What is the basic structural unit of a living ...,0.0279,0.3810,<NA>,<NA>,Not Reviewed
5,Why is friction called a necessary evil?,0.0000,0.0000,<NA>,<NA>,Not Reviewed
6,What is rolling friction?,0.0125,0.0870,<NA>,<NA>,Not Reviewed
7,What produces sound?,0.0000,0.0909,<NA>,<NA>,Not Reviewed
8,What determines the pitch of a sound?,0.0000,0.0000,<NA>,<NA>,Not Reviewed
9,What is a chloroplast?,0.0137,0.0714,<NA>,<NA>,Not Reviewed

In [129]:
# Error type summary 
error_summary = (
    analysis_df[
        "Error_Type"
    ]
    .value_counts()
    .reset_index()
)

error_summary.columns = [
    "Error_Type",
    "Count"
]

display(error_summary)

     Error_Type  Count
0  Not Reviewed      9
1    Acceptable      1

In [130]:
# Saving Error Analysis 
analysis_df.to_csv(
    "error_analysis.csv",
    index=False,
    encoding="utf-8"
)

print(
    "error_analysis.csv saved successfully!"
)

error_analysis.csv saved successfully!

In [131]:
# Final Summary 
print("=" * 60)
print("PART 5 — ERROR ANALYSIS SUMMARY")
print("=" * 60)

print(
    "Total interactions logged:",
    len(interaction_df)
)

print(
    "Average similarity:",
    round(
        interaction_df[
            "best_similarity"
        ].mean(),
        4
    )
)

print(
    "Average BLEU:",
    round(
        evaluation_df["BLEU"].mean(),
        4
    )
)

print(
    "Average ROUGE-L:",
    round(
        evaluation_df["ROUGE-L"].mean(),
        4
    )
)

print(
    "Average correctness:",
    round(
        evaluation_df[
            "Correctness"
        ].mean(),
        2
    )
)

print(
    "Average relevance:",
    round(
        evaluation_df[
            "Relevance"
        ].mean(),
        2
    )
)

print("=" * 60)

============================================================
PART 5 — ERROR ANALYSIS SUMMARY
============================================================
Total interactions logged: 10
Average similarity: 0.5529
Average BLEU: 0.0116
Average ROUGE-L: 0.0962
Average correctness: 4.0
Average relevance: 5.0
============================================================

In [133]:
%whos

Variable                   Type                          Data/Info
------------------------------------------------------------------
AutoModelForSeq2SeqLM      type                          <class 'transformers.mode<...>o.AutoModelForSeq2SeqLM'>
AutoTokenizer              type                          <class 'transformers.mode<...>tion_auto.AutoTokenizer'>
Document                   _RemoveLegacyFields           <class 'haystack.dataclasses.document.Document'>
HTML                       type                          <class 'IPython.core.display.HTML'>
InMemoryDocumentStore      type                          <class 'haystack.document<...>e.InMemoryDocumentStore'>
MODEL_NAME                 str                           google/flan-t5-small
OUTPUT_FILE                str                           class8_science.jsonl
PDF_OFFSET                 int                           13
PdfReader                  ABCMeta                       <class 'pypdf._reader.PdfReader'>
SIMILARITY_THRESHOLD       float                         0.4
SentenceTransformer        ABCMeta                       <class 'sentence_transfor<...>del.SentenceTransformer'>
SmoothingFunction          type                          <class 'nltk.translate.bl<...>score.SmoothingFunction'>
actual_chapters            set                           {np.int64(1), np.int64(2)<...>.int64(17), np.int64(18)}
analysis_df                DataFrame                     Shape: (10, 11)
ask_tutor                  function                      <function ask_tutor at 0x00000239826BFC40>
average_bleu               float64                       0.01158
average_rouge              float64                       0.09625
best_answer                Series                        Shape: (11,)
calculate_bleu             function                      <function calculate_bleu at 0x00000239826BED40>
calculate_rouge_l          function                      <function calculate_rouge<...>_l at 0x00000239826BF740>
chapter                    dict                          n=6
chapter_check              DataFrame                     Shape: (18, 5)
chapter_df                 DataFrame                     Shape: (18, 4)
chapter_distribution       DataFrame                     Shape: (18, 3)
chapter_locations          list                          n=18
chapter_number             int                           18
chapter_pages              list                          n=239
chapter_range              dict                          n=4
chapter_ranges             list                          n=18
chapter_ranges_df          DataFrame                     Shape: (18, 6)
chapter_records            list                          n=80
chapter_starts             list                          n=18
chapter_starts_df          DataFrame                     Shape: (18, 4)
chapters                   list                          n=18
chunk                      str                           Unless we all realise our<...>of your teachers. 2018-19
chunk_id                   int                           307
chunk_number               int                           2
chunk_text                 str                           walking on a busy road (F<...> congested road in a city
chunk_words                list                          n=65
chunks                     list                          n=2
classify_error             function                      <function classify_error at 0x000002398F5AC900>
clean_ncert_text           function                      <function clean_ncert_text at 0x00000239D4954FE0>
clean_text                 function                      <function clean_text at 0x00000239D4BE56C0>
cleaned                    str                           SCIENCE252\nObservations <...>hese agreements?\n2018-19
cleaned_pages              list                          n=264
combined_text              str                           CHEMICAL EFFECTS OF ELECT<...>f your teachers.\n2018-19
corpus                     list                          n=307
corpus_df                  DataFrame                     Shape: (307, 7)
corpus_file                str                           class8_science.jsonl
correctness_distribution   Series                        Shape: (1,)
create_chunks              function                      <function create_chunks at 0x00000239D4955B20>
create_prompt              function                      <function create_prompt at 0x00000239826BD6C0>
datetime                   type                          <class 'datetime.datetime'>
device                     device                        cpu
dimension                  int                           384
display                    function                      <function display at 0x00000239CAFE37E0>
document                   dict                          n=8
document_store             InMemoryDocumentStore         <haystack.document_stores<...>ct at 0x000002398100F0E0>
documents                  list                          n=307
embeddings                 ndarray                       307x384: 117888 elems, type `float32`, 471552 bytes (460.5 kb)
end_pdf                    int                           264
error_summary              DataFrame                     Shape: (2, 2)
evaluation_df              DataFrame                     Shape: (10, 11)
evaluation_results         list                          n=10
expected_chapters          set                           {1, 2, 3, 4, 5, 6, 7, 8, <...>, 13, 14, 15, 16, 17, 18}
f                          TextIOWrapper                 <_io.TextIOWrapper name='<...>ode='w' encoding='utf-8'>
faiss                      module                        <module 'faiss' from 'C:\<...>ges\\faiss\\__init__.py'>
first_record               dict                          n=5
found_page                 int                           12
generate_answer            function                      <function generate_answer at 0x00000239826BD8A0>
haystack_doc               Document                      Document(id=ec15d26d1a44e<...>52, 'printed_page': 239})
haystack_documents         list                          n=307
html                       str                           \n<!DOCTYPE html>\n<html <...>iv>\n\n</body>\n</html>\n
i                          int                           3
index                      IndexFlatIP                   <faiss.swigfaiss.IndexFla<...> at 0x00000239816725B0> >
interaction_df             DataFrame                     Shape: (10, 7)
interaction_logs           list                          n=10
is_in_scope                function                      <function is_in_scope at 0x00000239826BFD80>
item                       dict                          n=8
joblib                     module                        <module 'joblib' from 'C:<...>es\\joblib\\__init__.py'>
json                       module                        <module 'json' from 'C:\\<...>\Lib\\json\\__init__.py'>
line                       str                           {"id": "chunk_306", "chap<...>gested road in a city"}\n
llm                        T5ForConditionalGeneration    T5ForConditionalGeneratio<...>res=32128, bias=False)\n)
log_interaction            function                      <function log_interaction at 0x000002398D176E80>
low_rouge                  DataFrame                     Shape: (5, 10)
matches                    list                          n=8
missing_chapters           set                           set()
model                      SentenceTransformer           SentenceTransformer(\n  (<...>'sentence_embedding'})\n)
next_printed_start         int                           239
next_start                 int                           185
normalize_heading          function                      <function normalize_headi<...>ng at 0x00000239D4BE6020>
np                         module                        <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
os                         module                        <module 'os' from 'C:\\Us<...>\\anaconda3\\Lib\\os.py'>
page                       dict                          n=2
page_df                    DataFrame                     Shape: (239, 5)
page_normalized            str                           CHAPTER 11 FORCE AND PRES<...> CONTENTSCONTENTS 2018 19
pages                      list                          n=265
pd                         module                        <module 'pandas' from 'C:<...>es\\pandas\\__init__.py'>
pdf_end                    int                           252
pdf_page                   int                           265
pdf_page_number            int                           265
pdf_path                   str                           data/raw/class8_science.pdf
pdf_start                  int                           252
printed_page               int                           239
printed_start              int                           239
problematic                DataFrame                     Shape: (0, 11)
prompt                     str                           \nYou are an AI tutor for<...>iser\n\n\nFINAL ANSWER:\n
query                      str                           Who was the first Prime Minister of India?
question                   str                           What is friction?
rag_answer                 function                      <function rag_answer at 0x00000239826BF4C0>
re                         module                        <module 're' from 'C:\\Us<...>3\\Lib\\re\\__init__.py'>
reader                     PdfReader                     <pypdf._reader.PdfReader <...>ct at 0x00000239CBB1EF90>
record                     dict                          n=7
records                    list                          n=1
relevance_distribution     Series                        Shape: (1,)
requests                   module                        <module 'requests' from '<...>\\requests\\__init__.py'>
result                     dict                          n=2
results                    list                          n=3
review_columns             list                          n=8
review_df                  DataFrame                     Shape: (10, 8)
rouge                      RougeScorer                   <rouge_score.rouge_scorer<...>ct at 0x0000023985FF56A0>
rouge_scorer               module                        <module 'rouge_score.roug<...>_score\\rouge_scorer.py'>
semantic_search            function                      <function semantic_search at 0x0000023981119120>
sentence_bleu              function                      <function sentence_bleu at 0x0000023982A51D00>
smoothie                   method                        <bound method SmoothingFu<...>t at 0x0000023985FF5550>>
source                     dict                          n=3
start_pdf                  int                           185
target                     str                           POLLUTION OF AIR AND WATER
test_questions             list                          n=10
text                       str                           SCIENCE252\nObservations <...>se agreements?\n2018-19\n
texts                      list                          n=307
title                      str                           Pollution of Air and Water
tokenizer                  T5Tokenizer                   T5Tokenizer(name_or_path=<...>False, special=True),\n})
torch                      module                        <module 'torch' from 'C:\<...>ges\\torch\\__init__.py'>
tqdm                       type                          <class 'tqdm.auto.tqdm'>
valid_chapters             list                          n=17
weak_answers               DataFrame                     Shape: (5, 10)
words                      list                          n=365
worst_answer               Series                        Shape: (11,)

In [134]:
# ============================================================
# STEP 6.1 — SAVE RAG COMPONENTS
# ============================================================

import joblib
import faiss
import numpy as np

# Create a fresh FAISS index
faiss_index = faiss.IndexFlatIP(
    embeddings.shape[1]
)

# Make sure embeddings are float32
embedding_matrix = np.asarray(
    embeddings,
    dtype="float32"
)

# Add embeddings to FAISS
faiss_index.add(
    embedding_matrix
)

# Save FAISS index separately
faiss.write_index(
    faiss_index,
    "class8_science.faiss"
)

# Save documents and metadata
joblib.dump(
    documents,
    "class8_documents.joblib"
)

print("=" * 60)
print("RAG COMPONENTS SAVED")
print("=" * 60)

print(
    "Embedding model:",
    type(model).__name__
)

print(
    "Embedding dimensions:",
    embeddings.shape[1]
)

print(
    "FAISS vectors:",
    faiss_index.ntotal
)

print(
    "Documents:",
    len(documents)
)

print("\nFiles created:")
print("1. class8_science.faiss")
print("2. class8_documents.joblib")

============================================================
RAG COMPONENTS SAVED
============================================================
Embedding model: SentenceTransformer
Embedding dimensions: 384
FAISS vectors: 307
Documents: 307

Files created:
1. class8_science.faiss
2. class8_documents.joblib

In [135]:
# Verify the saved files 
import os

print(
    "FAISS file exists:",
    os.path.exists("class8_science.faiss")
)

print(
    "Documents file exists:",
    os.path.exists("class8_documents.joblib")
)

FAISS file exists: True
Documents file exists: True

In [136]:
# Load the saved FAISS index
test_index = faiss.read_index(
    "class8_science.faiss"
)

# Load saved documents
test_documents = joblib.load(
    "class8_documents.joblib"
)

print("=" * 60)
print("FAISS VERIFICATION")
print("=" * 60)

print(
    "FAISS vectors:",
    test_index.ntotal
)

print(
    "Documents:",
    len(test_documents)
)

print(
    "Embedding dimension:",
    test_index.d
)

============================================================
FAISS VERIFICATION
============================================================
FAISS vectors: 307
Documents: 307
Embedding dimension: 384

In [137]:
query = "What is friction?"

query_embedding = model.encode(
    [query],
    normalize_embeddings=True
)

query_embedding = np.asarray(
    query_embedding,
    dtype="float32"
)

scores, indices = test_index.search(
    query_embedding,
    3
)

print("QUESTION:")
print(query)

print("\nRETRIEVED DOCUMENTS:")
print("-" * 60)

for score, idx in zip(
    scores[0],
    indices[0]
):

    document = test_documents[idx]

    print(
        f"\nScore: {score:.4f}"
    )

    if isinstance(document, dict):

        print(
            "Chapter:",
            document.get("chapter", "Unknown")
        )

        print(
            "Page:",
            document.get(
                "printed_page",
                document.get("page", "Unknown")
            )
        )

        print(
            "Text:",
            document.get(
                "text",
                ""
            )[:300]
        )

    else:

        print(
            str(document)[:300]
        )

QUESTION:
What is friction?

RETRIEVED DOCUMENTS:
------------------------------------------------------------

Score: 0.6102
Chapter: Friction
Page: 146
Text: FRICTIONFRICTION Y ou might have seen a driver of a car or a truck slowing down the vehicle at a traffic signal. You, too, slow down your bicycle whenever needed by applying brakes. Have you ever thought why a vehicle slows down when brakes are applied? Not only vehicles, any object, moving over the

Score: 0.6054
Chapter: Friction
Page: 151
Text: FRICTION 151 12.4 Increasing and Reducing Friction As you have seen in the previous section, friction is desirable in some situations. Have you ever thought why the sole of your shoe is grooved [Fig. 12.11 (a)]? It is done to provide the shoes better grip on the floor, so that you can move safely. S

Score: 0.5814
Chapter: Friction
Page: 150
Text: SCIENCE150 the black board. Could it happen if there were no friction between the chalk and the board? If an object started moving, it would never stop if there were no friction. Had there been no friction between the tyres of the automobiles and the road, they could not be started or stopped or tur